const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const C=require('../core.js');
const market=require('../market.json');
const index=require('../daily-reports/index.json');
const reports=Object.fromEntries(index.reports.map(meta=>[meta.file,JSON.parse(fs.readFileSync(meta.file,'utf8'))]));
function boot(fetcher){const downloads=[],messages=[];const context=vm.createContext({InvestCore:C,market,state:C.empty(),location:{href:'https://example.github.io/app/#tab-dailyreport'},LegacyUI:{},route:'dailyreport',render(){},bindView(){},exportCSV(){throw Error('Current-market export must not be used for an archive');},document:{addEventListener(){},querySelectorAll(){return [];}},fetch:fetcher||async function(url){return {ok:true,json:async()=>C.clone(url==='daily-reports/index.json'?index:reports[url])};},download(...args){downloads.push(args);},toast(...args){messages.push(args);},URL,setTimeout(){}});context.window=context;vm.runInContext(fs.readFileSync('legacy-report-layout.js','utf8'),context);vm.runInContext(fs.readFileSync('daily-report-view.js','utf8'),context);return {context,downloads,messages};}
test('all archived sessions render original report sections and preserve their own dates and missing previous closes',()=>{const {context}=boot();for(const report of Object.values(reports)){const html=context.LegacyReportLayout.top(report,null)+context.LegacyReportLayout.main(report);assert.match(html,new RegExp(report.date));assert.match(html,/drSec3CardsContainer/);assert.match(html,/أبرز الفرص والأسهم النشطة/);if(Object.values(report.indices).some(q=>q.previous_close==null))assert.match(html,/إغلاق الجلسة السابقة:.*\n.*غير متاح/);assert.doesNotMatch(html,/صافي شراء 🟢|315\.4|52\.24|السيناريو الإيجابي الصاعد هو الراجح/);}});
test('archive CSV follows the selected session and includes funds, FX and provenance',async()=>{const app=boot();await app.context.ReportArchive.loadIndex();await app.context.ReportArchive.select('2026-10-04');app.context.exportCSV();const [name,content]=app.downloads[0];assert.equal(name,'dailyreport-2026-10-04.csv');assert.match(content,/"الجلسة","2026-10-04"/);assert.match(content,/"الصندوق","الاسم"/);assert.match(content,/usd_egp/);assert.match(content,/Commit المصدر/);assert.doesNotMatch(content,/"جلسة المصدر","2026-10-07"/);});
test('slow older report cannot overwrite a newer selection, and export is disabled while loading',async()=>{let hold=false,finish;const app=boot(async url=>{if(hold&&url==='daily-reports/2026-10-04.json')await new Promise(resolve=>{finish=resolve;});return {ok:true,json:async()=>C.clone(url==='daily-reports/index.json'?index:reports[url])};});await app.context.ReportArchive.loadIndex();hold=true;const older=app.context.ReportArchive.select('2026-10-04');assert.equal(app.context.ReportArchive.status().reportDate,null);app.context.exportCSV();assert.equal(app.downloads.length,0);await app.context.ReportArchive.select('2026-10-07');finish();await older;assert.equal(app.context.ReportArchive.status().reportDate,'2026-10-07');app.context.exportCSV();assert.equal(app.downloads[0][0],'dailyreport-2026-10-07.csv');});
test('wrong-session response fails closed instead of displaying or exporting another day',async()=>{const app=boot(async url=>({ok:true,json:async()=>url==='daily-reports/index.json'?C.clone(index):{...C.clone(reports[url]),date:'2026-10-01'}}));await app.context.ReportArchive.loadIndex();assert.equal(app.context.ReportArchive.status().reportDate,null);assert.match(app.context.ReportArchive.status().error,/لا يطابق/);app.context.exportCSV();assert.equal(app.downloads.length,0);});

test('switching from a slow weekly index to monthly cannot restore the older selection',async()=>{const periods=require('../period-reports/index.json');let calls=0,release;const app=boot(async url=>{if(url==='period-reports/index.json'){if(++calls===1)await new Promise(resolve=>release=resolve);return {ok:true,json:async()=>C.clone(periods)};}return {ok:true,json:async()=>C.clone(url==='daily-reports/index.json'?index:reports[url]||JSON.parse(fs.readFileSync(url,'utf8')))};});await app.context.ReportArchive.loadIndex();const older=app.context.ReportArchive.selectPeriod('weekly');await app.context.ReportArchive.selectPeriod('monthly');release();await older;assert.equal(app.context.ReportArchive.status().kind,'monthly');assert.equal(app.context.ReportArchive.status().selectedDate,'2026-09');assert.equal(app.context.ReportArchive.status().reportDate,'2026-09-30');});
