(function(){'use strict';
const esc=window.InvestCore.esc;let reports=null,selected='gemini';
const label=p=>p==='openai'?'ChatGPT · OpenAI':'Gemini';
function getReport(){const r=reports?.providers?.[selected]||(selected==='gemini'&&reports?.status?reports:null);if(r?.analysis){const sources=new Map((r.sources||[]).map(s=>[s.id,s]));if(!Array.isArray(r.analysis.findings)||r.analysis.findings.some(f=>!Array.isArray(f.source_ids)||!f.source_ids.length||f.source_ids.some(id=>sources.get(id)?.title!==f.fact)))return {...r,status:'failed',analysis:null,error_code:'حُجب التحليل: بعض الحقائق لا تطابق عناوين مصادرها.'};}return r;}
function text(v){return esc(typeof v==='string'?v:'');}
function sourceLinks(ids,report){const sources=new Map((report.sources||[]).map(s=>[s.id,s]));return (ids||[]).filter(id=>sources.has(id)).map(id=>{const s=sources.get(id);try{const u=new URL(s.url);if(u.protocol!=='https:')return '';return '<a href="'+esc(u.href)+'" target="_blank" rel="noopener noreferrer">'+text(s.publisher||s.title||id)+'</a>';}catch{return '';}}).join(' · ');}
function factsMarkup(r){const facts=(r.market_facts||[]).filter(q=>Number.isFinite(q.close)&&['historical_reference','verified'].includes(q.status));if(!facts.length)return '';const n=v=>Number.isFinite(v)?new Intl.NumberFormat('ar-EG',{maximumFractionDigits:4}).format(v):'غير متاح';return '<details><summary>الأسعار المرجعية المؤرخة ومصادرها</summary><p class="muted">أرقام من لقطة الأسعار، وليست أرقاماً ولّدها الذكاء الاصطناعي. راجع تاريخ كل جلسة؛ ليست بثاً لحظياً.</p><div class="table-scroll"><table><thead><tr><th>الأصل</th><th>السعر / المؤشر</th><th>التغير %</th><th>الجلسة</th><th>المصدر</th></tr></thead><tbody>'+facts.map(q=>'<tr><td>'+text(q.name)+'</td><td>'+n(q.close)+'</td><td>'+n(q.change_percent)+'</td><td>'+text(q.session_date)+'</td><td>'+sourceLinks([q.id],{sources:[{id:q.id,url:q.source_url,publisher:'المصدر'}]})+'</td></tr>').join('')+'</tbody></table></div></details>';}
function content(){const r=getReport();if(!r)return '<p class="warning">جار فحص حالة اتصال '+label(selected)+'…</p>';const status={waiting_key:'بانتظار اعتماد خدمة آمن في GitHub',failed:'تعذر توليد تحليل موثق',stale:r.reuse_reason==='six_hour_interval'?'آخر تحليل محفوظ؛ التحديث التالي بعد فترة الانتظار':'آخر تحليل محفوظ؛ تعذر تحديثه',ready:'تم توليد تحليل من الخدمة'}[r.status]||'حالة الاتصال غير مؤكدة';let html='<div class="ai-status '+(r.status==='ready'?'good':'warning')+'">'+esc(status)+'</div><p class="source">'+label(selected)+' · '+text(r.model||'')+'<br>توليد: '+text(r.generated_at||'لم يتم بعد')+' · جلسة الأسعار: '+text(r.market_session_date||r.input?.market_session_date||'غير محددة')+'</p>';
if(r.status==='waiting_key'){return html+'<p>الكود مجهّز للاتصال، لكن لم ينجح طلب فعلي بعد. يُحفظ الاعتماد في إعدادات المستودع الآمنة، ولا يُطلب داخل هذه الصفحة.</p>';}
if(r.error||r.error_code||r.message)html+='<p class="warning">'+text(r.message||r.error_code||r.error)+'</p>';
const a=r.analysis;if(!a)return html+'<p>لا يوجد تحليل صالح للعرض. لن نعرض إجابة قالبية باعتبارها ذكاءً اصطناعيًا.</p>';
html+=factsMarkup(r)+'<h3>قراءة الأدلة</h3><p>'+text(a.summary)+'</p>';
for(const f of a.findings||[])html+='<article class="ai-finding"><h4>ما يقوله المصدر</h4><p>'+text(f.fact)+'</p><h4>الأثر المحتمل — استنتاج</h4><p>'+text(f.possible_implication)+'</p><p class="warning">'+text(f.uncertainty)+'</p><p class="source">'+sourceLinks(f.source_ids,r)+'</p></article>';
if(a.scenarios?.length)html+='<h3>سيناريوهات مشروطة</h3>'+a.scenarios.map(s=>'<p><strong>'+text(s.label)+'</strong><br>'+text(s.condition)+'<br>'+text(s.possible_effect)+'<br>'+sourceLinks(s.source_ids,r)+'</p>').join('');
if(a.questions?.length)html+='<h3>ما يجب التحقق منه</h3><ul>'+a.questions.map(q=>'<li>'+text(q.question)+' '+sourceLinks(q.source_ids,r)+'</li>').join('')+'</ul>';
const limits=a.limitations||a.missing_information||[];if(limits.length)html+='<h3>حدود التحليل</h3><ul>'+limits.map(x=>'<li>'+text(x)+'</li>').join('')+'</ul>';
return html;}
function paint(){const area=document.getElementById('aiReportArea');if(area)area.innerHTML=content();document.querySelectorAll('[data-ai-provider]').forEach(b=>b.classList.toggle('active',b.dataset.aiProvider===selected));}
async function refresh(){try{const r=await fetch('ai.json',{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('unavailable');reports=await r.json();}catch{reports={providers:{gemini:{status:'failed',message:'تعذر تحميل حالة الخدمة'},openai:{status:'failed',message:'تعذر تحميل حالة الخدمة'}}};}paint();}
const button=document.createElement('button');button.id='aiAdvisorButton';button.className='ai-advisor-button';button.innerHTML='<span>✨</span> AI <small>المستشار الذكي</small>';button.type='button';button.setAttribute('aria-label','المستشار الذكي Gemini وChatGPT');document.body.append(button);
const dialog=document.createElement('dialog');dialog.id='aiAdvisorDialog';dialog.className='ai-advisor-dialog';dialog.innerHTML='<div class="title-row"><h2>✨ المستشار الذكي</h2><button type="button" id="closeAiDialog" aria-label="إغلاق المستشار">×</button></div><div class="ai-provider-tabs"><button data-ai-provider="gemini">Gemini</button><button data-ai-provider="openai">ChatGPT · OpenAI</button><button id="refreshAi">تحديث حالة التحليل</button></div><p class="muted">تحليل لبيانات السوق والأخبار العامة الموثقة. لا تُرسل الحيازات أو الكميات أو التكاليف أو أبحاثك الخاصة إلى أي مزود. التحديث دوري على الخادم؛ الزر يعيد تحميل النشرة المنشورة.</p><div id="aiReportArea" aria-live="polite"></div><p class="source">تراجع الأدلة الأصلية؛ صحة شكل الإجابة لا تضمن صحة استنتاجاتها. الأسعار في دفتر المحفظة منفصلة عن النص التحليلي.</p>';document.body.append(dialog);
button.addEventListener('click',()=>{dialog.showModal();paint();refresh();});document.getElementById('closeAiDialog').onclick=()=>dialog.close();document.getElementById('refreshAi').onclick=refresh;
dialog.querySelectorAll('[data-ai-provider]').forEach(b=>b.onclick=()=>{selected=b.dataset.aiProvider;paint();});
const css=document.createElement('style');css.textContent='.ai-advisor-button{position:fixed;z-index:25;left:20px;bottom:24px;border:1px solid #855cef;background:linear-gradient(105deg,#983ceb,#5267ee,#00b99a);color:white;border-radius:28px;padding:12px 18px;box-shadow:0 6px 28px #0008;font-size:15px;font-weight:700;display:flex;align-items:center;gap:9px}.ai-advisor-button small{color:white;font-size:11px}.ai-advisor-dialog{width:min(880px,calc(100% - 24px));max-width:880px}.ai-provider-tabs{display:flex;gap:8px;flex-wrap:wrap}.ai-provider-tabs .active{background:var(--accent);color:#06291e}.ai-status{border:1px solid currentColor;padding:9px 12px;border-radius:9px;margin:14px 0}.ai-finding{background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:16px;margin:14px 0}.ai-finding h4{margin:0;font-size:13px;color:var(--muted)}@media(max-width:620px){.ai-advisor-button{bottom:83px;left:10px;padding:8px 12px}.ai-advisor-button small{display:none}}@media print{.ai-advisor-button{display:none}}';document.head.append(css);refresh();
})();

