(function(){'use strict';
const esc=window.InvestCore.esc;let reports=null,selected='gemini',providerPicked=false;
const label=p=>p==='openai'?'ChatGPT · OpenAI':p==='groq'?'Groq · GPT-OSS 120B':'Gemini';
function getReport(provider=selected){
 const r=reports?.providers?.[provider]||(provider==='gemini'&&reports?.status?reports:null);
 if(!r?.analysis)return r?.status==='ready'?{...r,status:'failed',error_code:'invalid_response'}:r;
 try{
  const a=r.analysis;
  if(!Array.isArray(r.sources)||r.sources.some(source=>!source||typeof source.id!=='string'||typeof source.title!=='string'))throw Error();
  const sources=new Map(r.sources.map(source=>[source.id,source]));
  if(typeof a.summary!=='string'||!a.summary.trim()||!r.generated_at||!Number.isFinite(Date.parse(r.generated_at))||Date.parse(r.generated_at)>Date.now()||!Array.isArray(a.findings)||!a.findings.length||!Array.isArray(a.scenarios)||!Array.isArray(a.questions)||!Array.isArray(a.limitations))throw Error();
  if(a.findings.some(f=>!f||typeof f.fact!=='string'||!Array.isArray(f.source_ids)||!f.source_ids.length||f.source_ids.some(id=>sources.get(id)?.title!==f.fact)))throw Error();
  if([...a.scenarios,...a.questions].some(item=>!item||!Array.isArray(item.source_ids))||a.limitations.some(item=>typeof item!=='string'))throw Error();
 }catch{return {...r,status:'failed',analysis:null,error_code:'evidence_mismatch'};}
 return r;
}
function selectAvailableReport(){
 if(providerPicked)return;
 for(const status of ['ready','stale'])for(const provider of ['gemini','groq','openai']){
  const r=getReport(provider);
  if(r?.status===status&&r.analysis){selected=provider;return;}
 }
 selected='gemini';
}
function text(v){return esc(typeof v==='string'?v:'');}
function when(v){if(!v||!Number.isFinite(Date.parse(v)))return 'لم يتم بعد';return new Intl.DateTimeFormat('ar-EG-u-nu-latn',{dateStyle:'medium',timeStyle:'short',timeZone:'Africa/Cairo'}).format(new Date(v))+' بتوقيت القاهرة';}
function problem(code){return ({http_429:'رفض مزود الخدمة الطلب بسبب حدود الاستخدام أو رصيد API. يراجع مالك التطبيق الرصيد والحدود قبل إعادة المحاولة.',insufficient_quota:'لا توجد حصة API متاحة. يراجع مالك التطبيق الرصيد وحدود الإنفاق لدى OpenAI.',credit_balance_exhausted:'رصيد API لدى OpenAI غير كافٍ. يحتاج مالك التطبيق إلى مراجعة إعدادات الفوترة.',organization_spend_limit_exceeded:'وصل حساب OpenAI إلى حد الإنفاق المحدد.',project_spend_limit_exceeded:'وصل مشروع OpenAI إلى حد الإنفاق المحدد.',organization_usage_limit_exceeded:'وصل حساب OpenAI إلى حد الاستخدام المسموح.',rate_limit_exceeded:'بلغ الطلب حد سرعة الاستخدام؛ ستُحترم فترة الانتظار قبل المحاولة التالية.',slow_down:'طلب مزود الخدمة تقليل سرعة الطلبات. ستُحترم فترة الانتظار.',invalid_api_key:'رفض مزود الخدمة بيانات الاعتماد. يراجع مالك التطبيق السر المحفوظ دون إرساله في المحادثة.',authentication_error:'تعذر اعتماد اتصال الخدمة. يراجع مالك التطبيق إعدادات الاتصال الآمنة.',permission_denied:'لا يملك الاعتماد الصلاحية اللازمة لهذا الطلب.',http_401:'رفض مزود الخدمة بيانات الاعتماد.',http_403:'رفض مزود الخدمة صلاحية الوصول؛ يلزم مراجعة صلاحيات المشروع وإتاحة الخدمة.',http_400:'رفض مزود الخدمة صيغة الطلب؛ يحتاج موصل الخدمة إلى مراجعة.',http_500:'واجه مزود الخدمة مشكلة مؤقتة.',http_503:'الخدمة غير متاحة مؤقتًا.',daily_call_limit:'بلغت الخدمة سقف الطلبات اليومي؛ تُحفظ آخر نتيجة مع تاريخها.',new_evidence_waiting_interval:'توجد أخبار أحدث؛ سيُحدّث التحليل بعد فترة الانتظار وحدود الطلبات.',invalid_response:'لم تجتز الإجابة فحص الأدلة وجودة البيانات، لذلك لم تُعرض.',blocked_or_incomplete:'لم يكتمل الرد من الخدمة، لذلك لم يُعرض تحليل غير مكتمل.',evidence_mismatch:'حُجب التحليل لأن بعض الحقائق لا تطابق عناوين مصادرها.',timeout:'لم تصل إجابة مكتملة خلال المهلة؛ سيحترم التحديث التالي فترة الانتظار.',no_valid_public_news:'لا تتوفر أخبار عامة موثقة كافية للتوليد.',invalid_public_input:'تعذر التحقق من بيانات السوق أو الأخبار اللازمة للتحليل.'})[code]||'تعذر تحديث التحليل حاليًا. تُحفظ آخر نتيجة صحيحة إن كانت متاحة.';}
function sourceLinks(ids,report){const sources=new Map((report.sources||[]).map(s=>[s.id,s]));return (ids||[]).filter(id=>sources.has(id)).map(id=>{const s=sources.get(id);try{const u=new URL(s.url);if(u.protocol!=='https:')return '';return '<a href="'+esc(u.href)+'" target="_blank" rel="noopener noreferrer">'+text(s.publisher||s.title||id)+'</a>';}catch{return '';}}).join(' · ');}
function factsMarkup(r){const facts=(Array.isArray(r.market_facts)?r.market_facts:[]).filter(q=>q&&Number.isFinite(q.close)&&['historical_reference','verified'].includes(q.status));if(!facts.length)return '';const n=v=>Number.isFinite(v)?new Intl.NumberFormat('en-US',{maximumFractionDigits:4}).format(v):'غير متاح';return '<details><summary>الأسعار المرجعية المؤرخة ومصادرها</summary><p class="muted">أرقام من لقطة الأسعار، وليست أرقاماً ولّدها الذكاء الاصطناعي. راجع تاريخ كل جلسة؛ ليست بثاً لحظياً.</p><div class="table-scroll"><table><thead><tr><th>الأصل</th><th>السعر / المؤشر</th><th>التغير %</th><th>الجلسة</th><th>المصدر</th></tr></thead><tbody>'+facts.map(q=>'<tr><td>'+text(q.name)+'</td><td>'+n(q.close)+'</td><td class="font-mono">'+n(q.change_percent)+'</td><td>'+text(q.session_date)+'</td><td>'+sourceLinks([q.id],{sources:[{id:q.id,url:q.source_url,publisher:'المصدر'}]})+'</td></tr>').join('')+'</tbody></table></div></details>';}
function content(){const r=getReport();if(!r)return '<p class="warning">جار فحص حالة اتصال '+label(selected)+'…</p>';const status={waiting_key:'بانتظار إعداد اتصال الخدمة الآمن',failed:'تعذر توليد تحليل موثق',stale:r.reuse_reason==='six_hour_interval'?'آخر تحليل محفوظ؛ التحديث التالي بعد فترة الانتظار':'آخر تحليل محفوظ؛ تعذر تحديثه',ready:'تم توليد تحليل من الخدمة'}[r.status]||'حالة الاتصال غير مؤكدة';let html='<div class="ai-status '+(r.status==='ready'?'good':'warning')+'">'+esc(status)+'</div><p class="source">'+label(selected)+' · '+text(r.model||'')+'<br>توليد: '+text(when(r.generated_at))+' · جلسة الأسعار: '+text(r.market_session_date||r.input?.market_session_date||'غير محددة')+'</p>';
if(r.status==='waiting_key'){return html+'<p>الكود مجهّز للاتصال، لكن لم ينجح طلب فعلي بعد. يُحفظ الاعتماد في إعدادات المستودع الآمنة، ولا يُطلب داخل هذه الصفحة.</p>';}
if(r.error||r.error_code||r.message)html+='<p class="warning">'+text(r.message==='تعذر تحميل حالة الخدمة'?'تعذر تحميل حالة الخدمة. أعد تحميل الصفحة للتحقق من الاتصال.':problem(r.error_code||r.error))+'</p>';
const a=r.analysis;if(!a)return html+'<p>لا يوجد تحليل صالح للعرض. لن نعرض إجابة قالبية باعتبارها ذكاءً اصطناعيًا.</p>';
html+=factsMarkup(r)+'<h3>قراءة الأدلة</h3><p>'+text(a.summary)+'</p>';
for(const f of a.findings||[])html+='<article class="ai-finding"><h4>ما يقوله المصدر</h4><p>'+text(f.fact)+'</p><h4>الأثر المحتمل — استنتاج</h4><p>'+text(f.possible_implication)+'</p><p class="warning">'+text(f.uncertainty)+'</p><p class="source">'+sourceLinks(f.source_ids,r)+'</p></article>';
if(a.scenarios?.length)html+='<h3>سيناريوهات مشروطة</h3>'+a.scenarios.map(s=>'<p><strong>'+text(s.label)+'</strong><br>'+text(s.condition)+'<br>'+text(s.possible_effect)+'<br>'+sourceLinks(s.source_ids,r)+'</p>').join('');
if(a.questions?.length)html+='<h3>ما يجب التحقق منه</h3><ul>'+a.questions.map(q=>'<li>'+text(q.question)+' '+sourceLinks(q.source_ids,r)+'</li>').join('')+'</ul>';
const limits=a.limitations||a.missing_information||[];if(limits.length)html+='<h3>حدود التحليل</h3><ul>'+limits.map(x=>'<li>'+text(x)+'</li>').join('')+'</ul>';
return html;}
function paint(){const area=document.getElementById('aiReportArea');if(area)area.innerHTML=(!providerPicked&&selected!=='gemini'?'<p class="source" role="status">اختيرت نشرة '+label(selected)+' تلقائيًا وفق حالة التحليل. راجع تاريخ التوليد أدناه.</p>':'')+content();document.querySelectorAll('[data-ai-provider]').forEach(b=>b.classList.toggle('active',b.dataset.aiProvider===selected));const automatic=document.getElementById('autoAiProvider');if(automatic)automatic.classList.toggle('active',!providerPicked);}
async function refresh(){try{const r=await fetch('ai.json',{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error('unavailable');reports=await r.json();}catch{reports={providers:{gemini:{status:'failed',message:'تعذر تحميل حالة الخدمة'},groq:{status:'failed',message:'تعذر تحميل حالة الخدمة'},openai:{status:'failed',message:'تعذر تحميل حالة الخدمة'}}};}selectAvailableReport();paint();}
let config=null,popup=null,connected=false,busy=false,chatProvider='groq',connections={},context={},history=[],lastPlan=[];
const requests=new Map();
const template=document.createElement('template');template.innerHTML=window.LegacyTemplates.advisor;const button=template.content.firstElementChild;button.id='aiAdvisorButton';button.removeAttribute('data-legacy-click');button.type='button';button.setAttribute('aria-label','المستشار الذكي والمحادثة');document.body.append(button);
const dialog=document.createElement('dialog');dialog.id='aiAdvisorDialog';dialog.className='workspace-ui ai-advisor-dialog';
dialog.innerHTML='<div class="title-row"><h2>✨ المستشار الذكي</h2><button type="button" id="closeAiDialog" aria-label="إغلاق المستشار">×</button></div><div class="ai-provider-tabs"><button data-ai-tab="chat" class="active">المحادثة</button><button data-ai-tab="newsletter">النشرة المؤرخة</button><button id="connectAi">ربط خدمة المحادثة</button></div><p id="aiConnectionStatus" class="ai-status warning" role="status">جار فحص إعداد الخدمة…</p><section id="aiChatPane"><div class="ai-provider-tabs" aria-label="مزود المحادثة"><button type="button" data-chat-provider="groq" class="active">Groq · GPT-OSS 120B</button><button type="button" data-chat-provider="gemini">Gemini 3.8 Flash</button><button type="button" data-chat-provider="openai">ChatGPT · OpenAI</button></div><div id="aiChatMessages" class="ai-chat-messages" aria-live="polite"></div><div id="aiRepairPlan"></div><label class="ai-context-choice"><input id="aiSharePortfolio" type="checkbox">إرسال ملخص الحيازات والكميات والتكاليف مع السؤال</label><p class="muted" id="aiContextLabel">يُرسل السؤال وسياق الصفحة وبيانات السوق العامة المؤرخة. ملخص المحفظة يحتاج اختيارك.</p><form id="aiConversationForm"><label for="aiConversationInput">رسالتك</label><textarea id="aiConversationInput" maxlength="6000" placeholder="اكتب سؤالك، ويمكنك متابعة الحوار بسؤال آخر…" required></textarea><div class="actions"><button id="aiSend" class="primary">إرسال</button><button type="button" id="aiClear">محادثة جديدة</button></div></form></section><section id="aiNewsletterPane" hidden><div class="ai-provider-tabs"><button type="button" id="autoAiProvider">اختيار تلقائي</button><button data-ai-provider="gemini">Gemini</button><button data-ai-provider="groq">Groq · GPT-OSS</button><button data-ai-provider="openai">OpenAI</button><button id="refreshAi">تحديث النشرة</button></div><p class="muted">النشرة المؤرخة مستقلة عن اتصال المحادثة. تُعرض حالة آخر توليد وتاريخ بياناته لكل مزود.</p><div id="aiReportArea"></div></section>';
document.body.append(dialog);
const get=id=>dialog.querySelector('#'+id);
function status(message,ok=false){get('aiConnectionStatus').textContent=message;get('aiConnectionStatus').className='ai-status '+(ok?'good':'warning');}
async function loadConfig(){try{const r=await fetch('app-config.json',{cache:'no-store'});if(!r.ok)throw Error();config=await r.json();if(!config.aiServicePublished)status('لم تُنشر إعدادات خدمة المحادثة الخاصة بعد.');else status('اضغط ربط خدمة المحادثة لتسجيل الدخول إلى خدمتك الخاصة.');}catch{status('تعذر قراءة إعداد خدمة المحادثة.');}}
function paintChat(){get('aiChatMessages').innerHTML=history.length?history.map(m=>'<article class="ai-chat-message '+m.role+'"><b>'+ (m.role==='user'?'أنت':'المساعد')+'</b><div>'+esc(m.content)+'</div></article>').join(''):'<p class="muted">تدعم المحادثة سياق الأسئلة المتتابعة. تظهر الإجابة بعد استلام رد فعلي من الخدمة.</p>';if(busy)get('aiChatMessages').insertAdjacentHTML('beforeend','<p role="status">جار إعداد الإجابة…</p>');get('aiSend').disabled=busy;get('aiConversationInput').disabled=busy;get('aiClear').disabled=busy;get('aiChatMessages').scrollTop=get('aiChatMessages').scrollHeight;dialog.querySelectorAll('[data-chat-provider]').forEach(b=>{b.disabled=busy;b.classList.toggle('active',b.dataset.chatProvider===chatProvider);});}
function buildContext(){const data={page:route,calendar:window.MarketCalendarUI?.context(),market:{session_date:market.session_date,indices:market.indices,assets:Object.fromEntries(Object.entries(market.assets).map(([t,q])=>[t,{name:q.name,type:q.type,close:q.close,previous_close:q.previous_close,session_date:q.session_date,status:q.status,source_url:q.source_url}]))},news:(externalNews?.items||[]).slice(0,12).map(x=>({title:x.title,date:x.published_at||x.date,url:x.url,publisher:x.publisher})),...context};delete data.question;if(get('aiSharePortfolio').checked){const p=C.portfolio(state,market);data.portfolio={cash:p.cashKnown?p.cash:null,complete:p.complete,positions:p.positions.map(h=>({symbol:h.ticker,quantity:h.qty,cost:h.cost,value:h.value,unrealized:h.unrealized})),fees:p.fees,feesComplete:p.feesComplete};}return data;}
function connect(){if(!config?.aiServicePublished)return status('افتح خدمة المحادثة الخاصة لربط المزود المحدد واختبار استجابته.');if(popup&&!popup.closed){popup.focus();return status(connected?'خدمة المحادثة متصلة.':'أكمل تسجيل الدخول في نافذة الخدمة.',connected);}popup=window.open(config.aiServiceUrl,'investment-ai-service','popup,width=760,height=820');if(!popup)return status('لم تفتح نافذة الخدمة. اسمح بالنافذة ثم اضغط الربط مجدداً.');connected=false;status('أكمل تسجيل الدخول في نافذة الخدمة، ثم عد إلى سؤالك.');}
function request(payload){return new Promise((resolve,reject)=>{if(!connected||!popup||popup.closed)return reject(Error('اربط '+label(chatProvider)+' من نافذة الخدمة أولاً.'));const id=crypto.randomUUID(),timer=setTimeout(()=>{requests.delete(id);reject(Error('لم تصل إجابة من الخدمة؛ أعد الربط أو المحاولة.'));},65000);requests.set(id,{resolve,reject,timer});popup.postMessage({type:'investment-ai-request',id,payload:{...payload,provider:chatProvider}},new URL(config.aiServiceUrl).origin);});}
window.addEventListener('message',event=>{if(!config?.aiServicePublished||event.origin!==new URL(config.aiServiceUrl).origin||event.source!==popup)return;if(event.data?.type==='investment-ai-ready'){connections=event.data.providers||{gemini:{configured:event.data.configured===true}};connected=connections[chatProvider]?.configured===true;const current=connections[chatProvider];status(current?.message||(connected?'المفتاح محفوظ؛ ننتظر رداً فعلياً من '+label(chatProvider)+'.':'لم يُربط مفتاح '+label(chatProvider)+' بعد.'),current?.connected===true);return;}if(event.data?.type!=='investment-ai-response')return;const pending=requests.get(event.data.id);if(!pending)return;clearTimeout(pending.timer);requests.delete(event.data.id);if(event.data.error)pending.reject(Error(event.data.error));else if(typeof event.data.result?.reply!=='string'||!event.data.result.reply.trim())pending.reject(Error('لم تصل إجابة صالحة من الخدمة.'));else pending.resolve(event.data.result);});
function paintPlan(result){lastPlan=[];const box=get('aiRepairPlan');box.innerHTML='';if(context.kind!=='audit'||!result.repairs?.length)return;try{lastPlan=SystemAudit.validatePlan(result.repairs,context.audit);box.innerHTML='<h3>اقتراحات الإصلاح</h3>'+lastPlan.map((p,i)=>'<article class="ai-finding"><p>'+esc(p.explanation)+'</p><p class="source font-mono">'+esc(p.findingId)+' · '+esc(p.actionId)+'</p><button type="button" data-ai-apply="'+i+'">تطبيق الإصلاح وإعادة الفحص</button></article>').join('');}catch{box.textContent='لم تجتز خطة الإصلاح مطابقة نتائج الفحص؛ لم يُطبّق تغيير.';}}
get('aiConversationForm').onsubmit=async event=>{event.preventDefault();const value=get('aiConversationInput').value.trim();if(!value||busy)return;if(!connected)return connect();const next=[...history.slice(-24),{role:'user',content:value}];history=next;busy=true;get('aiConversationInput').value='';paintChat();try{const result=await request({messages:next,context:buildContext(),mode:context.kind==='audit'?'audit':'chat'});history.push({role:'assistant',content:result.reply});status('استجابة فعلية من '+result.provider+' · '+result.model,true);paintPlan(result);}catch(err){history=next.slice(0,-1);get('aiConversationInput').value=value;status(err.message);}finally{busy=false;paintChat();}};
dialog.addEventListener('click',async event=>{const b=event.target.closest('[data-ai-apply]');if(!b)return;const p=lastPlan[Number(b.dataset.aiApply)];if(!p)return;b.disabled=true;try{await SystemAuditUI.repair(p.findingId,p.actionId);b.textContent='تم التحقق من الإصلاح';context.audit=SystemAuditUI.latest();}catch(err){b.textContent='لم ينجح الإصلاح؛ لم يُعتمد التغيير';status(err.message);} });
function open(next={}){context=next;get('aiContextLabel').textContent=next.kind==='audit'?'يُرسل تقرير الفحص والأخطاء المقاسة ومعرفات الإصلاحات المتاحة. ملخص المحفظة يحتاج اختيارك.':'يُرسل السؤال وسياق الصفحة وبيانات السوق العامة المؤرخة. ملخص المحفظة يحتاج اختيارك.';if(!dialog.open)dialog.showModal();switchTab('chat');if(next.question)get('aiConversationInput').value=String(next.question).slice(0,6000);else if(next.kind==='audit')get('aiConversationInput').value='راجع نتائج الفحص، واشرح المشكلات واقترح الإصلاحات الممكنة ضمن النطاق المسموح.';paintChat();}
function switchTab(tab){get('aiChatPane').hidden=tab!=='chat';get('aiNewsletterPane').hidden=tab!=='newsletter';dialog.querySelectorAll('[data-ai-tab]').forEach(b=>b.classList.toggle('active',b.dataset.aiTab===tab));if(tab==='newsletter')refresh();}
button.onclick=()=>open();get('closeAiDialog').onclick=()=>dialog.close();get('connectAi').onclick=connect;get('aiClear').onclick=()=>{history=[];context={};lastPlan=[];get('aiRepairPlan').innerHTML='';get('aiConversationInput').value='';get('aiSharePortfolio').checked=false;paintChat();};get('refreshAi').onclick=refresh;get('autoAiProvider').onclick=()=>{providerPicked=false;selectAvailableReport();paint();};dialog.querySelectorAll('[data-ai-provider]').forEach(b=>b.onclick=()=>{selected=b.dataset.aiProvider;providerPicked=true;paint();});dialog.querySelectorAll('[data-ai-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.aiTab));
dialog.querySelectorAll('[data-chat-provider]').forEach(b=>b.onclick=()=>{chatProvider=b.dataset.chatProvider;connected=connections[chatProvider]?.configured===true;const c=connections[chatProvider];status(c?.message||(connected?'المفتاح محفوظ؛ أرسل السؤال للتحقق من الاستجابة.':'اربط '+label(chatProvider)+' من نافذة الخدمة الخاصة.'),c?.connected===true);paintChat();});
window.AIAdvisor={open,scan:async image=>{if(chatProvider==='groq')throw Error('اختر Gemini أو ChatGPT في المستشار لقراءة الصور؛ Groq المتصل يدعم النصوص.');if(!connected){connect();throw Error('أكمل تفعيل المفتاح والربط ثم أعد قراءة الصورة.');}return request({mode:'scan',image});},status:()=>({configured:config?.aiServicePublished===true,connected,busy,provider:chatProvider,providers:connections})};
const css=document.createElement('style');css.textContent='.ai-advisor-dialog{width:min(880px,calc(100% - 24px));max-width:880px}.ai-provider-tabs{display:flex;gap:8px;flex-wrap:wrap}.ai-provider-tabs .active{background:var(--accent);color:#06291e}.ai-status{border:1px solid currentColor;padding:9px 12px;border-radius:9px;margin:14px 0}.ai-finding,.ai-chat-message{background:var(--surface);border:1px solid var(--line);border-radius:12px;padding:14px;margin:10px 0}.ai-chat-messages{max-height:42vh;min-height:100px;overflow:auto}.ai-chat-message.user{border-color:#6366f166}.ai-chat-message b{font-size:12px;color:var(--accent)}.ai-chat-message div{white-space:pre-wrap;overflow-wrap:anywhere;font-size:15px;line-height:1.8;margin-top:5px}.ai-context-choice{display:flex;gap:7px;align-items:center}.ai-context-choice input{width:auto;margin:0}.ai-finding h4{margin:0;font-size:13px;color:var(--muted)}@media print{#aiAdvisorButton,#aiAdvisorDialog{display:none}}';document.head.append(css);paintChat();loadConfig();refresh();
})();
