/* Pure calculations for original interface controls. Never changes the investment ledger. */
(function(root){'use strict';
const positive=(v,name,zero=false)=>{if(v===''||v==null||!Number.isFinite(Number(v))||Number(v)<(zero?0:Number.MIN_VALUE))throw Error(name+' غير صالح');return Number(v);};
function dca(qty,oldPrice,newPrice,target){qty=positive(qty,'الكمية');oldPrice=positive(oldPrice,'متوسط الشراء');newPrice=positive(newPrice,'سعر الإضافة');target=positive(target,'المتوسط المستهدف');if(!(newPrice<target&&target<oldPrice))throw Error('لخفض المتوسط يجب أن يكون سعر الإضافة أقل من المتوسط المستهدف، والمستهدف أقل من المتوسط الحالي');const added=Math.ceil(qty*(oldPrice-target)/(target-newPrice));if(!Number.isSafeInteger(added))throw Error('الكمية المطلوبة خارج نطاق الحساب');return {added,cost:added*newPrice,average:(qty*oldPrice+added*newPrice)/(qty+added)};}
function allocation(amount,strategy){amount=positive(amount,'الفائض',true);const weights={balanced:[.7,.15,.15],growth:[.85,.15,0],hedged:[.5,.25,.25]}[strategy];if(!weights)throw Error('اختر استراتيجية صالحة');const stock=Math.round(amount*weights[0]*100)/100,gold=Math.round(amount*weights[1]*100)/100;return {stock,gold,cash:Math.round((amount-stock-gold)*100)/100};}
function fees(amount,feeRate,taxableProfit,taxRate){amount=positive(amount,'قيمة الأمر');feeRate=positive(feeRate,'نسبة الرسوم',true);taxableProfit=positive(taxableProfit,'الربح الخاضع',true);taxRate=positive(taxRate,'نسبة الضريبة',true);if(feeRate>100||taxRate>100)throw Error('النسب يجب أن تكون بين 0 و100');return {fee:amount*feeRate/100,tax:taxableProfit*taxRate/100,total:amount*feeRate/100+taxableProfit*taxRate/100};}
// Limited educational case: male decedent, at least one living son, only the entered heirs.
// Sources: Dar al-Ifta fatwas 12382 and 11507. Other cases require a complete heirs review.
function inheritance(wealth,wives,sons,daughters,parents){wealth=positive(wealth,'صافي التركة',true);wives=positive(wives,'عدد الزوجات',true);sons=positive(sons,'عدد الأبناء',true);daughters=positive(daughters,'عدد البنات',true);if(![wives,sons,daughters].every(Number.isInteger)||wives>4||sons>1000||daughters>1000)throw Error('أدخل أعداداً صحيحة للورثة');if(!['none','mother','father','both'].includes(parents))throw Error('اختيار الوالدين غير صالح');if(sons<1)throw Error('هذه الحاسبة تدعم وجود ابن حي واحد على الأقل. الحالات الأخرى تحتاج حصر بقية الورثة ومراجعة مختص');const wife=wives?wealth/8:0,mother=['mother','both'].includes(parents)?wealth/6:0,father=['father','both'].includes(parents)?wealth/6:0,unit=(wealth-wife-mother-father)/(sons*2+daughters);return {wifeEach:wives?wife/wives:0,wifeTotal:wife,mother,father,sonEach:unit*2,daughterEach:unit,total:wife+mother+father+sons*unit*2+daughters*unit};}
function matchesStock(symbol,q,kind,owned,search,sector,change){if(!((symbol+' '+q.name+' '+(q.sector||'')).toLowerCase().includes((search||'').toLowerCase())))return false;if(sector&&sector!=='all'&&q.sector!==sector)return false;const finite=Number.isFinite,margin=finite(q.margin)?q.margin:finite(q.fair_value)?(q.fair_value-q.close)/q.fair_value*100:null;switch(kind){case 'all':return true;case 'portfolio':return owned.includes(symbol);case 'gainers':return change!=null&&change>0;case 'losers':return change!=null&&change<0;case 'unchanged':return change===0;case 'oversold':return finite(q.rsi)&&q.rsi<=35;case 'overbought':return finite(q.rsi)&&q.rsi>=70;case 'opportunities':return finite(margin)&&margin>0&&q.rsi!=null&&q.rsi<70;case 'threats':return finite(q.rsi)&&q.rsi>=70||finite(margin)&&margin<0;case 'breakout':return finite(q.resistance)&&q.close>q.resistance;case 'dollar_earners':return finite(q.foreign_revenue_share)&&q.foreign_revenue_share>0;case 'bluechip':return q.bluechip===true;case 'margin':return finite(margin)&&margin>=30;case 'low_pe':return finite(q.pe)&&q.pe>0&&q.pe<10;case 'dividends':return finite(q.dividend_yield)&&q.dividend_yield>0;case 'near_support':return finite(q.support)&&q.support>0&&q.close>=q.support&&q.close/q.support<=1.03;case 'insiders':return q.insider_net_buy>0;case 'divergence':return q.bullish_divergence===true;default:return false;}}
function matchesFund(symbol,q,kind){switch(kind){case 'all':return true;case 'gold':return q.type==='gold'||symbol==='AZG';case 'equity_funds':return q.type==='fund'&&symbol!=='AZG';case 'usd':return q.currency==='USD';case 'high_yield':return Number.isFinite(q.annual_yield)&&q.annual_yield>=20;case 'daily_liquidity':return q.liquidity==='daily';default:return false;}}
function goals(target,current,monthly,annual,volatility,months=120,seed=20261008){target=positive(target,'الهدف');current=positive(current,'الرصيد',true);monthly=positive(monthly,'المساهمة',true);annual=Number(annual);volatility=positive(volatility,'التقلب',true);if(!Number.isFinite(annual)||annual<=-100||annual>100||volatility>200||!Number.isInteger(months)||months<1||months>1200)throw Error('افتراضات المحاكاة خارج النطاق');let x=seed>>>0;const rand=()=>{x=(Math.imul(1664525,x)+1013904223)>>>0;return (x+.5)/4294967296;};const values=[],sigma=volatility/100,drift=(Math.log(1+annual/100)-sigma*sigma/2)/12;for(let path=0;path<1000;path++){let value=current;for(let m=0;m<months;m++){const z=Math.sqrt(-2*Math.log(rand()))*Math.cos(2*Math.PI*rand());value=value*Math.exp(drift+sigma/Math.sqrt(12)*z)+monthly;}values.push(value);}values.sort((a,b)=>a-b);return {p10:values[100],median:values[500],p90:values[900],probability:values.filter(v=>v>=target).length/values.length*100,paths:values.length,months};}
const api={dca,allocation,fees,inheritance,matchesStock,matchesFund,goals};if(typeof module==='object'&&module.exports)module.exports=api;else root.InterfaceTools=api;
})(typeof globalThis==='object'?globalThis:this);
