/* Original controls receive explicit, scoped actions; financial records remain in InvestCore. */
(function(){'use strict';
const L=window.LegacyUI,T=window.InterfaceTools,u=L.ui,n=L.n,e=C.esc,key='egx_independent_tools_v1';
let extra={alerts:[],journal:[],activity:[],activityHidden:false},activityFilter='all',perfPeriod='ALL',aiFilter='all';
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&['alerts','journal','activity'].every(k=>Array.isArray(saved[k])))extra={...extra,...saved};}catch{}
function save(){localStorage.setItem(key,JSON.stringify(extra));}
function log(kind,text){extra.activity.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),kind,text});extra.activity=extra.activity.slice(0,500);save();}
const output=(id,markup)=>{const el=$(id);if(el){el.classList.remove('hidden');el.innerHTML=markup;}return el;};
const metric=(label,value)=>'<div class="flex justify-between gap-3 text-xs py-1"><span class="text-slate-300">'+e(label)+'</span><b class="font-mono text-emerald-300">'+n(value)+' ج.م</b></div>';
function modal(title,body){document.querySelectorAll('dialog.legacy-control-dialog').forEach(x=>x.close());const d=document.createElement('dialog');d.className='legacy-control-dialog';d.innerHTML='<div class="flex justify-between items-center gap-3 border-b border-slate-800 pb-3 mb-3"><h2 class="font-bold text-sm">'+e(title)+'</h2><button type="button" class="text-slate-400 p-1" aria-label="إغلاق">✕</button></div>'+body;d.querySelectorAll('[id]').forEach(el=>{el.dataset.localId=el.id;el.id='tool_dialog_'+el.id;});d.querySelector('button').onclick=()=>d.close();d.addEventListener('close',()=>d.remove(),{once:true});document.body.append(d);d.showModal();return d;}
function options(selector,rows,first){const el=$(selector);if(!el)return;const value=el.value;el.innerHTML=(first?'<option value="all">'+e(first)+'</option>':'')+rows.map(([v,label])=>'<option value="'+e(v)+'">'+e(label)+'</option>').join('');if([...el.options].some(o=>o.value===value))el.value=value;}
function selectNews(){const all=externalNews?.items||[],funds=u.newsTab==='funds',term=(u.newsSearch||'').toLowerCase();return all.filter(x=>(funds?x.category!=='stock':x.category==='stock')&&((x.title+' '+x.publisher+' '+(x.symbols||[]).join(' ')).toLowerCase().includes(term))&&(funds?(!u.newsFund||u.newsFund==='all'||(x.symbols||[]).includes(u.newsFund)):(!u.newsSource||u.newsSource==='all'||x.publisher===u.newsSource||x.source_id===u.newsSource)&&(!u.newsTicker||u.newsTicker==='all'||(x.symbols||[]).includes(u.newsTicker))&&(!u.newsSector||u.newsSector==='all'||(x.symbols||[]).some(t=>market.assets[t]?.sector===u.newsSector))));}
function paintNews(){const id=u.newsTab==='funds'?'newsFundsFeedContainer':'newsStocksFeedContainer';if($(id))$(id).innerHTML=selectNews().map(window.LegacyMarketCards.news).join('')||'<p class="text-xs text-slate-400 py-5">لا توجد أخبار موثقة تطابق هذه التصفية.</p>';}
function activate(selector,chosen,theme='emerald'){document.querySelectorAll(selector).forEach(b=>{const active=b===chosen;b.setAttribute('aria-pressed',String(active));b.classList.toggle('bg-'+theme+'-600',active);b.classList.toggle('text-white',active);b.classList.toggle('ring-1',active);b.classList.toggle('ring-'+theme+'-400',active);});}
function paintExtras(){const alerts=$('alertsListContainer');if(alerts)alerts.innerHTML=extra.alerts.map(a=>{const q=market.assets[a.symbol],value=a.condition.startsWith('rsi')?q?.rsi:q?.close,hit=value!=null&&(a.condition==='price_below'?value<a.target:a.condition==='price_above'?value>a.target:a.condition==='rsi_oversold'?value<35:value>70);return '<div class="flex justify-between items-center gap-2 p-2 rounded-lg bg-slate-900 border border-slate-800 text-xs"><span><b class="font-mono">'+e(a.symbol)+'</b> · '+e(a.condition)+' · <b class="font-mono">'+n(a.target)+'</b></span><span class="'+(hit?'text-amber-300':'text-slate-400')+'">'+(value==null?'المؤشر غير متاح':hit?'تحقق في اللقطة':'لم يتحقق')+'</span><button data-remove-alert="'+e(a.id)+'" class="text-rose-400" aria-label="حذف التنبيه">✕</button></div>';}).join('')||'<p class="text-xs text-slate-400">لا توجد تنبيهات مسجلة. تفحص الشروط عند تحديث المصدر، دون إشعارات خلفية.</p>';
 if(alerts&&extra.alertsUndo)alerts.insertAdjacentHTML('beforeend','<button data-undo-alert class="text-sky-300 text-xs font-bold mt-2">تراجع عن حذف التنبيه</button>');
 const journal=$('dj_list');if(journal)journal.innerHTML=extra.journal.map(j=>'<article class="p-2 rounded-lg bg-slate-900 border border-slate-800"><div class="flex justify-between"><b class="font-mono">'+e(j.symbol)+'</b><span>'+e(j.type)+' · '+e(j.date.slice(0,10))+'</span></div><p>'+e(j.reason)+'</p><p>'+e(j.notes)+'</p></article>').join('')||'<p class="text-slate-400">لا توجد قرارات مسجلة بعد.</p>';
 const feed=$('userActivityFeedContainer');if(feed){const events=extra.activity.filter(x=>activityFilter==='all'||x.kind===activityFilter);feed.innerHTML=extra.activityHidden?'<p class="text-xs text-slate-400">أُخفي سجل العرض؛ دفتر العمليات محفوظ.</p><button data-restore-activity class="text-sky-300 text-xs">استعادة عرض السجل</button>':events.map(x=>'<div class="rounded-xl bg-slate-900 border border-slate-800 p-2.5 text-xs"><div class="flex justify-between"><b>'+e(x.text)+'</b><span class="font-mono text-slate-400">'+e(x.date.slice(0,16).replace('T',' '))+'</span></div></div>').join('')||'<p class="text-xs text-slate-400">لا توجد أنشطة في هذه التصفية.</p>';if(!extra.activityHidden&&(activityFilter==='all'||activityFilter==='trade'||activityFilter==='adjust'))feed.insertAdjacentHTML('beforeend',L.workspace(transactionsView()));}
 const health=$('toolSubViewHealth');if(health){const spans=health.querySelectorAll('.p-3\\.5 .font-mono'),p=C.portfolio(state,market),largest=p.value>0?Math.max(0,...p.positions.map(h=>(h.value??0)/p.value*100)):null;health.querySelectorAll('span').forEach(s=>{if(s.textContent.includes('كلاودز ~56%'))s.textContent='1. السيولة المسجلة في دفتر الحسابات:';});const vals=['فحوص موثقة','النقد: '+(p.cashKnown?n(p.cash)+' ج':'غير موثق'),'فئات الأصول: '+new Set(p.positions.map(h=>h.assetType)).size,'التحقق الشرعي يحتاج مستنداً مؤرخاً','أكبر وزن: '+(largest==null?'غير متاح':n(largest,1)+'%')];spans.forEach((s,i)=>s.textContent=vals[i]||'غير متاح');}
}
function period(preset){perfPeriod=preset;const today=localDate(),d=new Date(today+'T00:00:00Z');if(preset==='1D')d.setUTCDate(d.getUTCDate()-1);if(preset==='1W')d.setUTCDate(d.getUTCDate()-7);if(preset==='1M')d.setUTCMonth(d.getUTCMonth()-1);if(preset==='3M')d.setUTCMonth(d.getUTCMonth()-3);if(preset==='YTD')d.setUTCMonth(0,1);const start=preset==='ALL'?'0001-01-01':d.toISOString().slice(0,10);return {start,end:today};}
function performanceDialog(preset){const dates=period(preset||perfPeriod),d=modal('تحليل أداء الفترة','<div class="grid grid-cols-2 gap-2 text-xs"><label>من<input data-period-start type="date" value="'+dates.start+'" class="w-full bg-slate-900 border border-slate-700 p-2 rounded-xl font-mono"></label><label>إلى<input data-period-end type="date" value="'+dates.end+'" class="w-full bg-slate-900 border border-slate-700 p-2 rounded-xl font-mono"></label></div><button data-period-calculate class="bg-indigo-600 text-white text-xs rounded-xl p-2 my-3">حساب الفترة</button><div data-period-result></div>'+L.workspace(L.baseViews.performance()));bindView(d);const calc=()=>{try{const start=d.querySelector('[data-period-start]').value,end=d.querySelector('[data-period-end]').value;C.date(start);C.date(end);if(start>end)throw Error('بداية الفترة بعد نهايتها');const rows=state.transactions.filter(t=>t.date>=start&&t.date<=end),fees=rows.reduce((a,t)=>a+(t.fee||0),0),income=rows.filter(t=>t.type==='dividend').reduce((a,t)=>a+t.amount,0);d.querySelector('[data-period-result]').innerHTML='<p class="text-xs text-slate-300 font-mono">'+e(start)+' ← '+e(end)+'</p>'+metric('الرسوم المسجلة في الفترة',fees)+metric('التوزيعات المسجلة في الفترة',income)+'<p class="text-xs text-slate-400">'+rows.length+' عملية. العائد الكامل للفترة يحتاج تقييمات حدود الفترة وتدفقاتها؛ لا يُستبدل بربح الامتلاك.</p>';}catch(err){d.querySelector('[data-period-result]').textContent=err.message;}};d.querySelector('[data-period-calculate]').onclick=calc;calc();}
function feesDialog(){const root=L.fragment('tools'),box=L.by(root,'fee_tax_output').closest('.glass-card'),d=modal('حاسبة رسوم التنفيذ',box.outerHTML);d.querySelector('p').textContent='أدخل النسب الفعلية من كشف التنفيذ أو المرجع الضريبي الذي ينطبق عليك.';const controls=d.querySelector('[data-local-id=fee_tax_output]');controls.insertAdjacentHTML('beforebegin','<div class="grid grid-cols-2 gap-2 my-2 text-xs"><label>نسبة الرسوم الفعلية %<input id="actualFeeRate" type="number" min="0" max="100" step="any" value="0" class="w-full bg-slate-900 border border-slate-700 p-2 rounded-xl font-mono"></label><label>نسبة الضريبة المعتمدة %<input id="actualTaxRate" type="number" min="0" max="100" step="any" value="0" class="w-full bg-slate-900 border border-slate-700 p-2 rounded-xl font-mono"></label></div>');const b=d.querySelector('[data-legacy-click]');b.removeAttribute('data-legacy-click');b.onclick=()=>{try{const val=id=>d.querySelector('[data-local-id="'+id+'"],#'+id).value,r=T.fees(val('fee_trade_val'),val('actualFeeRate'),val('fee_capital_gain'),val('actualTaxRate'));controls.classList.remove('hidden');controls.innerHTML=metric('رسوم التنفيذ',r.fee)+metric('الضريبة بحسب النسبة المدخلة',r.tax)+metric('المجموع',r.total)+'<p>حساب تقديري للنسب التي أدخلتها؛ يعتمد القيد على كشف التنفيذ الفعلي.</p>';}catch(err){controls.classList.remove('hidden');controls.textContent=err.message;}};}
function scanner(){const d=modal('استيراد كشف ومراجعة بيانات الصورة','<p class="text-xs text-slate-300 mb-3">استورد ملف محفظة JSON، أو افتح صورة كشفك لمراجعتها وتسجيل العملية.</p><div class="flex gap-2 text-xs"><button data-scanner-import class="bg-emerald-600 rounded-xl p-2 text-white">استيراد ملف المحفظة</button><button data-scanner-entry class="bg-slate-800 rounded-xl p-2">تسجيل أرقام الصورة</button></div><label class="block text-xs text-slate-400 mt-4">صورة الكشف للمعاينة المحلية<input data-scanner-image type="file" accept="image/*" class="block my-2"></label><img data-scanner-preview alt="معاينة كشف المستخدم" hidden class="rounded-xl w-full"><p class="text-[11px] text-slate-400 mt-2">المعاينة محلية؛ لم تُستخرج الأرقام تلقائيًا ولا تُرسل الصورة إلى AI.</p>');d.querySelector('[data-scanner-import]').onclick=()=>$('fileInput').click();d.querySelector('[data-scanner-entry]').onclick=()=>{d.close();openEntry();};let url;d.querySelector('[data-scanner-image]').onchange=ev=>{const f=ev.target.files[0];if(!f)return;if(!f.type.startsWith('image/')||f.size>8000000)return toast('اختر صورة أقل من 8 MB',true);if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);const img=d.querySelector('img');img.src=url;img.hidden=false;};d.addEventListener('close',()=>{if(url)URL.revokeObjectURL(url);});}
function exportExcel(){if(!window.XLSX)return toast('تعذر تحميل محرّك إكسيل',true);let rows,name=route+'-'+localDate();if(route==='performance'&&window.PerformanceUI?.csvRows()){rows=PerformanceUI.csvRows();name='performance-'+PerformanceUI.result().start+'-'+PerformanceUI.result().end;}else if(route==='dailyreport'){rows=window.ReportArchive?.rows();if(!rows)return toast('انتظر تحميل التقرير المختار',true);name='dailyreport-'+window.ReportArchive.status().reportDate;}else if(route==='radar')rows=[['الرمز','الاسم','النوع','السعر','الجلسة','المصدر'],...Object.entries(market.assets).map(([t,q])=>[t,q.name,q.type,q.close,q.session_date,q.source_url])];else{const p=C.portfolio(state,market);rows=[['الرمز','الكمية','التكلفة','السعر','القيمة','الربح غير المحقق'],...p.positions.map(h=>[h.ticker,h.qty,h.cost,h.price,h.value,h.unrealized])];}const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(rows),'البيانات');if(route!=='dailyreport'){if(route!=='radar'){const p=C.portfolio(state,market);for(const [type,title]of [['stock','الأسهم'],['fund','الصناديق'],['gold','الذهب']])XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['الرمز','الكمية','التكلفة','السعر','القيمة','غير المحقق','جلسة التقييم'],...p.positions.filter(h=>h.assetType===type).map(h=>[h.ticker,h.qty,h.cost,h.price,h.value,h.unrealized,h.quote?.session_date])]),title);XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['النقد الموثق',p.cashKnown?p.cash:null],['الثروة',p.totalWealth],['رسوم مدفوعة',p.fees],['الرسوم مكتملة',p.feesComplete?'نعم':'لا']]),'النقد والثروة');}XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(state.transactions),'العمليات');XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(extra.journal),'القرارات');}XLSX.writeFile(book,name+'.xlsx');}
function ai(context){if(window.AIAdvisor)return window.AIAdvisor.open(context);$('aiAdvisorButton')?.click();}
const handlers={
 openThndrScannerModal:scanner,openThndrFeePolicyModal:feesDialog,calculateThndrFeesAndTaxes:feesDialog,
 openPeriodPerformanceModal:()=>performanceDialog(perfPeriod),setPerformancePeriodPreset:a=>{performanceDialog(a[0]);},
 setSectorFilter:a=>{u.sector=a[0];render();},sortDividendsTable:a=>{u.dividendSort=a[0];render();},
 openPivotModal:a=>{const q=market.assets[a[0]],h=state.histories[a[0]]?.candles?.at(-1);if(!h)return modal('المحاور السعرية · '+a[0],'<p class="text-xs text-slate-400">ارفع سجل OHLC حقيقي من الشارت لحساب المحاور؛ لا تتوفر أعلى وأدنى الجلسة في لقطة السعر الحالية.</p><button data-open-history="'+e(a[0])+'" class="bg-sky-900 text-sky-300 rounded-xl p-2 text-xs mt-3">فتح الشارت واستيراد السلسلة</button>');const pivot=(h.high+h.low+h.close)/3;return modal('المحاور السعرية · '+a[0],metric('Pivot',pivot)+metric('R1',2*pivot-h.low)+metric('S1',2*pivot-h.high)+'<p class="text-xs font-mono">'+e(h.date)+' · '+e(q?.name||a[0])+'</p>');},
 openStockValuation:a=>L.showEditor('research',a[0]),
 openCustomAlertModal:a=>{u.toolsTab='alerts';go('tools');if(a[0]&&$('alertStockSelect'))$('alertStockSelect').value=a[0];$('alertTargetVal')?.focus();},
 addUserAlert:()=>{const symbol=$('alertStockSelect').value,condition=$('alertConditionSelect').value;if(!market.assets[symbol])throw Error('اختر أصلاً له مصدر سعر في التطبيق');const target=condition==='rsi_oversold'?35:condition==='rsi_overbought'?70:C.num($('alertTargetVal').value,'القيمة المستهدفة',Number.MIN_VALUE);extra.alerts.push({id:crypto.randomUUID(),symbol,condition,target});log('adjust','إضافة تنبيه '+symbol);save();paintExtras();},
 saveDecisionJournalEntry:()=>{const symbol=$('dj_ticker').value,notes=$('dj_notes').value.trim();if(!notes)throw Error('أدخل مبرر القرار قبل حفظه');extra.journal.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),symbol,type:$('dj_type').value,reason:$('dj_reason').selectedOptions[0].textContent,notes});log('adjust','توثيق قرار '+symbol);save();paintExtras();$('dj_notes').value='';toast('حُفظ القرار محلياً؛ لم تُنفّذ صفقة');},
 runDcaCalculation:()=>{const r=T.dca($('calc_q1').value,$('calc_p1').value,$('calc_p2').value,$('calc_target').value);output('calc_dca_output',metric('المبلغ الإضافي قبل الرسوم',r.cost)+metric('المتوسط بعد الإضافة',r.average)+'<p class="font-mono">الكمية الإضافية: '+r.added+'</p>');},
 runSurplusAllocation:()=>{const r=T.allocation($('advisor_surplus_val').value,$('advisor_strategy').value);output('advisor_output',metric('الأسهم بحسب الخطة',r.stock)+metric('الذهب بحسب الخطة',r.gold)+metric('السيولة بحسب الخطة',r.cash)+'<p class="text-[11px] text-slate-400">توزيع حسابي للخطة التي اخترتها؛ لا يحدد أسهماً للشراء.</p>');},
 runGoalsMonteCarloSimulation:()=>{const r=T.goals($('goal_target').value,$('goal_current').value,$('goal_monthly').value,$('goal_rate').value,$('goal_volatility').value);output('goal_output',metric('الوسيط بعد 120 شهراً',r.median)+metric('المئين العاشر',r.p10)+metric('المئين التسعين',r.p90)+'<p class="font-mono text-xs">بلوغ الهدف داخل النموذج: '+n(r.probability,1)+'%</p><p class="text-[11px] text-slate-400">1000 مسار بعائد وتقلب تفترضهما، دون رسوم أو تضخم. الاحتمال وصف للنموذج؛ ليس ضماناً أو توقعاً موثقاً للسوق.</p>');},
 calculateZakat:a=>{const investor=a[0]==='investor';if(investor){const d=modal('زكاة ريع الاستثمار','<p class="text-xs text-slate-300">للأسهم غير التجارية المقتناة للريع، أدخل الريع الذي تحققت فيه شروط الزكاة، وليس القيمة السوقية.</p><input data-zakat-base type="number" min="0" value="'+C.portfolio(state,market).income+'" class="w-full bg-slate-900 border border-slate-700 p-2 rounded-xl font-mono my-3"><button data-zakat-calculate class="bg-emerald-600 text-white rounded-xl p-2 text-xs">حساب ربع العشر</button><div data-zakat-result></div>');d.querySelector('[data-zakat-calculate]').onclick=()=>{try{const v=C.num(d.querySelector('input').value,'الريع');d.querySelector('[data-zakat-result]').innerHTML=zakatMarkup(v);}catch(err){d.querySelector('[data-zakat-result]').textContent=err.message;}};return;}output('zakat_output',zakatMarkup(C.num($('zakat_val').value,'الوعاء الزكوي')));},
 calculateInheritanceDistribution:()=>{const r=T.inheritance($('inh_wealth_val').value,$('inh_wives').value,$('inh_sons').value,$('inh_daughters').value,$('inh_parents').value);output('inh_output',metric('نصيب كل زوجة',r.wifeEach)+metric('نصيب الأم إن كانت موجودة',r.mother)+metric('نصيب الأب إن كان موجوداً',r.father)+metric('نصيب كل ابن',r.sonEach)+metric('نصيب كل بنت',r.daughterEach)+'<p class="text-[11px] text-slate-400">مثال تعليمي لرجل له ابن حي على الأقل والورثة المدخلون فقط، على صافي التركة بعد الحقوق السابقة. الحالات الأخرى تحتاج مراجعة مختص.</p><a href="https://dar-alifta.org/ar/fatwa/details/12382" target="_blank" rel="noopener" class="text-sky-300 text-xs">مرجع دار الإفتاء</a>');},
 renderRecommendationsView:()=>{render();toast('أُعيدت قراءة أبحاثك ولقطة السوق الحالية');},
 filterAiQuestions:a=>{aiFilter=a[0];decorate();},
 analyzeFilteredNews:a=>{const id=a[0]==='funds'?'filteredNewsAnalysisReportFunds':'filteredNewsAnalysisReport',box=$(id);box?.classList.remove('hidden');if(box){box.querySelectorAll('[data-news-analysis-status]').forEach(x=>x.remove());const result=box.querySelector('[id*="Body"],[id*="Content"],[id*="Text"]')||box;result.insertAdjacentHTML('beforeend','<p data-news-analysis-status class="text-xs text-slate-400">'+selectNews().length+' عنواناً يطابق التصفية. يراجع AI العناوين العامة مع تاريخها ومصدرها.</p>');}ai({kind:'news',items:selectNews().slice(0,15)});},
 filterUserActivity:a=>{activityFilter=a[0];paintExtras();},
 clearUserActivityLog:()=>{extra.activityHidden=true;save();paintExtras();},
 exportUserActivityLog:()=>download('activity-'+localDate()+'.csv',C.csv([['التاريخ','النوع','النشاط'],...extra.activity.map(x=>[x.date,x.kind,x.text])]),'text/csv;charset=utf-8'),
 exportMultiSheetExcel:exportExcel,exportUniversalExcel:exportExcel,
 runComprehensiveSystemAudit:()=>window.SystemAuditUI?.run(),diagnoseAuditWithGemini:()=>window.SystemAuditUI?.diagnose(),
 askGeminiDailyReportSummary:()=>ai({kind:'report',report:window.ReportArchive?.context()}),
 submitMarketAiQuestion:()=>ai({question:$('marketAiCustomInput')?.value||''}),sendUserAiQuestion:()=>ai({question:$('aiChatInput')?.value||''})
};
function zakatMarkup(v){return metric('ربع العشر عند تحقق شروط الوجوب',v*.025)+'<p class="text-[11px] text-slate-400">حساب مشروط ببلوغ النصاب والحول الهجري وتحديد الوعاء وخصم الديون، مع مراعاة نوع الشركة وقصد الاقتناء وعدم تكرار زكاة أخرجتها الشركة عنك.</p><a href="https://dar-alifta.org/ar/fatwa/details/22181" target="_blank" rel="noopener" class="text-sky-300 text-xs">مرجع دار الإفتاء</a>';}
function run(call,name,args,el){const dismiss=call.match(/^document\.getElementById\('([^']+)'\)\.classList\.add\('hidden'\)$/);if(dismiss){$(dismiss[1])?.classList.add('hidden');return true;}if(handlers[name]){try{handlers[name](args,el);}catch(err){const result={runDcaCalculation:'calc_dca_output',calculateInheritanceDistribution:'inh_output',calculateZakat:'zakat_output',runSurplusAllocation:'advisor_output',runGoalsMonteCarloSimulation:'goal_output'}[name];if(result)output(result,'<p class="text-xs text-rose-400">'+e(err.message)+'</p>');else toast(err.message,true);}return true;}if(/gemini|askai|floatingai|testGeminiApiKey|pasteAndSaveGeminiKey/i.test(name)){ai({kind:/settings|key/i.test(name)?'connection':'chat',symbol:market.assets[args[0]]?args[0]:null,question:market.assets[args[0]]?'تحليل '+args[0]:args[0]||''});return true;}return false;}
function decorate(){if(route==='news'){options('newsSourceFilterSelect',[...new Set((externalNews?.items||[]).map(x=>x.publisher))].map(x=>[x,x]),'كل المصادر المتاحة');options('newsStockTickerSelect',Object.entries(market.assets).filter(([,q])=>q.type==='stock').map(([t,q])=>[t,t+' · '+q.name]),'جميع الأسهم المتاحة');options('newsSectorFilterSelect',[...new Set(Object.values(market.assets).map(q=>q.sector).filter(Boolean))].map(x=>[x,x]),'كل القطاعات الموثقة');options('newsFundFilterSelect',Object.entries(market.assets).filter(([,q])=>q.type!=='stock').map(([t,q])=>[t,t+' · '+q.name]),'كل الأصول المتاحة');for(const [id,k]of [['newsSourceFilterSelect','newsSource'],['newsStockTickerSelect','newsTicker'],['newsSectorFilterSelect','newsSector'],['newsFundFilterSelect','newsFund']])if($(id))$(id).value=u[k]||'all';if($('newsStockSearchInput'))$('newsStockSearchInput').value=u.newsSearch||'';paintNews();}
 if(route==='tools'){const rows=Object.entries(market.assets).map(([t,q])=>[t,t+' · '+q.name]);options('alertStockSelect',rows);options('dj_ticker',rows);for(const [id,value]of Object.entries(extra.drafts||{})){const field=$(id);if(field&&field.closest('#view')&&field.type!=='file')field.value=value;}paintExtras();}
 if(route==='radar'){options('valuationStockSelect',Object.entries(market.assets).filter(([,q])=>q.type==='stock').map(([t,q])=>[t,t+' · '+q.name]));paintValuation();}
 for(const b of document.querySelectorAll('#view [data-legacy-click]')){const call=b.dataset.legacyClick;for(const [fn,val]of [['setFilter',u.radarFilter],['setFundsFilter',u.fundsFilter],['setRecActionFilter',u.recAction],['setRecTypeFilter',u.recType],['switchNewsSubTab',u.newsTab],['switchMarketSubTab',u.marketTab],['switchRecAnalysisSlicer',u.researchTab],['filterUserActivity',activityFilter]]){if(call.startsWith(fn+'(')){const active=call.match(/'([^']+)'/)?.[1]===val;b.setAttribute('aria-pressed',String(active));b.classList.toggle('ring-1',active);b.classList.toggle('ring-emerald-400',active);}}}
 document.querySelectorAll('[data-ai-category],[data-category],[data-cat]').forEach(card=>{if(card.closest('#recSlicerPanel_analysis'))card.classList.toggle('hidden',aiFilter!=='all'&&(card.dataset.aiCategory||card.dataset.category||card.dataset.cat)!==aiFilter);});
}
function paintValuation(){const select=$('valuationStockSelect'),box=$('valuationCardContainer');if(!select||!box)return;const q=market.assets[select.value],r=state.research[select.value]||{};box.innerHTML='<div class="p-3 rounded-xl bg-slate-900 border border-slate-800 text-xs">'+metric('السعر المرجعي',q?.close)+'<p class="text-slate-400">'+e(q?.session_date||'')+' · '+(r.eps>0?'ربحية السهم المدخلة '+n(r.eps):'أدخل ربحية السهم ومضاعفات السيناريوهات مع مصدر القوائم لحساب نطاق القيمة.')+'</p><button data-open-history="'+e(select.value)+'" class="text-sky-300 font-bold mt-2">فتح بحث وتقييم السهم</button></div>';}
document.addEventListener('change',async ev=>{const id=ev.target.id;if(route==='tools'&&ev.target.tagName==='SELECT'){extra.drafts=extra.drafts||{};extra.drafts[id]=ev.target.value;save();}if(['newsSourceFilterSelect','newsSectorFilterSelect','newsStockTickerSelect','newsFundFilterSelect'].includes(id)){u[{newsSourceFilterSelect:'newsSource',newsSectorFilterSelect:'newsSector',newsStockTickerSelect:'newsTicker',newsFundFilterSelect:'newsFund'}[id]]=ev.target.value;paintNews();}if(id==='valuationStockSelect')paintValuation();if(ev.target.dataset.legacyChange==='restorePortfolioData(event)'){const f=ev.target.files[0];if(f)try{await importObject(JSON.parse(await f.text()));}catch(err){toast(err.message,true);}}});
document.addEventListener('input',ev=>{if(route==='tools'&&ev.target.id&&ev.target.closest('#view')&&ev.target.type!=='file'){extra.drafts=extra.drafts||{};extra.drafts[ev.target.id]=ev.target.value;save();}if(['newsStockSearchInput','newsFundsSearchInput'].includes(ev.target.id)){u.newsSearch=ev.target.value;paintNews();}});
document.addEventListener('click',ev=>{const a=ev.target.closest('[data-open-history]');if(a)L.showEditor('research',a.dataset.openHistory);const rm=ev.target.closest('[data-remove-alert]');if(rm){extra.alertsUndo=[...extra.alerts];extra.alerts=extra.alerts.filter(x=>x.id!==rm.dataset.removeAlert);save();paintExtras();toast('حُذف التنبيه؛ يمكنك التراجع عن الحذف');}if(ev.target.closest('[data-undo-alert]')&&extra.alertsUndo){extra.alerts=extra.alertsUndo;delete extra.alertsUndo;save();paintExtras();}if(ev.target.closest('[data-restore-activity]')){extra.activityHidden=false;save();paintExtras();}});
const previous=render;render=function(){previous();decorate();};const refresh=refreshMarket;refreshMarket=async function(){await refresh();log('sync','إعادة تحميل أسعار جلسة '+market.session_date);};const priorBackup=backup;backup=function(){download('investment-backup-'+localDate()+'.json',JSON.stringify({application:'egypt-investment-workspace',exported_at:new Date().toISOString(),state,tools:extra},null,2));};const previousImport=importObject;importObject=async function(obj){const revision=state.revision;await previousImport(obj);if(state.revision!==revision&&obj.tools&&['alerts','journal','activity'].every(k=>Array.isArray(obj.tools[k]))){extra={...extra,...obj.tools};save();render();}};
window.LegacyActions={run,handlers:Object.keys(handlers),decorate,exportExcel,selectNews,extra:()=>extra};render();
})();
