/* Original chart presentation and sector bar markup, fed by InvestCore and archive data. */
(function(){'use strict';
let charts=[];
const colors=['#10b981','#0ea5e9','#f59e0b','#8b5cf6','#ec4899','#64748b','#14b8a6','#f97316'];
function allocationData(){const p=C.portfolio(state,market),groups={};for(const h of p.positions){if(h.value==null||h.value<=0)continue;const label=h.quote?.sector||({stock:'أسهم — القطاع غير موثق',fund:'صناديق استثمار',gold:'ذهب'}[h.assetType]||'أصول أخرى');groups[label]=(groups[label]||0)+h.value;}if(p.cashKnown&&p.cash>0)groups['السيولة المسجلة']=p.cash;return groups;}
function sectorBars(groups){const total=Object.values(groups).reduce((a,v)=>a+v,0);return Object.entries(groups).sort((a,b)=>b[1]-a[1]).map(([name,value],i)=>{const pct=value/total*100,color=['#0ea5e9','#10b981','#f59e0b','#8b5cf6','#ec4899','#64748b','#14b8a6','#f97316'][i%8];return `<div class="space-y-1"><div class="flex items-center justify-between text-[11px]"><span class="text-slate-300 font-medium flex items-center gap-1.5"><span class="w-2 h-2 rounded-full inline-block" style="background-color:${color}"></span><span>${e(name)}</span></span><span class="font-mono text-white font-bold">${pct.toFixed(1)}% <span class="text-slate-400 font-normal">(${value.toLocaleString('en-US',{maximumFractionDigits:0})} ج)</span></span></div><div class="w-full bg-slate-800/80 rounded-full h-1.5 overflow-hidden"><div class="h-full rounded-full transition-all duration-500" style="width:${Math.min(pct,100)}%;background-color:${color}"></div></div></div>`;}).join('')||'<div class="text-slate-500 text-center py-2 text-xs">لا توجد أصول لعرض توزيع القطاعات</div>';}
function paint(){if(!window.Chart)return;const donut=$('portfolioDonutChart');if(donut){const groups=allocationData(),labels=Object.keys(groups),values=Object.values(groups);$('portfolioSectorBars').innerHTML=sectorBars(groups);if(values.length)charts.push(new Chart(donut.getContext('2d'),{type:'doughnut',data:{labels,datasets:[{data:values,backgroundColor:colors,borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{color:'#94a3b8',font:{family:'Cairo',size:10},boxWidth:10}}},cutout:'68%'}}));}
 for(const canvas of document.querySelectorAll('[data-chart-labels]')){const labels=JSON.parse(canvas.dataset.chartLabels),values=JSON.parse(canvas.dataset.chartValues),rsi=canvas.dataset.chartKind==='rsi';charts.push(new Chart(canvas.getContext('2d'),{type:'bar',data:{labels,datasets:[{data:values,backgroundColor:values.map(v=>v==null?'transparent':rsi?v>=70?'rgba(248,113,113,0.9)':v<=35?'rgba(52,211,153,0.9)':'rgba(56,189,248,0.85)':v>=0?'rgba(52,211,153,0.85)':'rgba(248,113,113,0.85)'),borderRadius:4,borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:ctx=>rsi?'مؤشر القوة النسبية RSI(14): '+format(ctx.raw,1):'نسبة التغير اليومية: '+pct(ctx.raw)}}},scales:{x:{ticks:{color:'#94a3b8',font:{size:labels.length>15?8:9,weight:'bold'},maxRotation:labels.length>15?60:0,autoSkip:false},grid:{color:'rgba(255,255,255,0.03)'}},y:{...(rsi?{min:0,max:100}:{}),ticks:{color:'#94a3b8',font:{size:9},...(rsi?{}:{callback:v=>(v>=0?'+':'')+v+'%'})},grid:{color:'rgba(255,255,255,0.06)'}}}}}));}
}
const previous=render;render=function(){for(const chart of charts)chart.destroy();charts=[];previous();paint();};render();
})();
