(function(){'use strict';const P=PerformanceEngine,L=LegacyUI;let range=null,presetCode='1M',datesOpen=false,reports=[],loaded=false,loading=false,result=null,loadError='';
const n=L.n,pc=L.pc,field='w-full bg-slate-950 border border-slate-700 rounded-xl p-2 font-mono text-xs',money=(r,id,v)=>L.put(r,id,v==null?'غير متاح':n(v)+' ج');
function chosen(){if(!range||range.preset!=='CUSTOM')range=P.preset(presetCode,market.session_date,state);return range;}
function label(root,id,text){const b=L.by(root,id)?.parentElement?.firstElementChild;if(b)b.textContent=text;}
function renderPerformance(){const root=L.fragment('performance');let r;try{r=P.calculate(state,market,chosen(),reports);result=r;}catch(error){root.insertAdjacentHTML('beforeend','<p class="text-xs text-rose-400">'+e(error.message)+'</p>');return root.outerHTML;}
 root.querySelector('h2').nextElementSibling.textContent='نتائج دفتر العمليات للفترة المختارة، مع تواريخ ومصادر التقييم';
 const presets=root.querySelector('.perf-preset-btn').parentElement;
 presets.insertAdjacentHTML('afterend','<div id="performancePeriodStatus" aria-live="polite" class="text-[10px] text-slate-400 font-mono">'+e(r.start)+' ← '+e(r.end)+' · '+r.transactions.length+' عملية · '+(loading?'تحميل الأرشيف…':loaded?'الأرشيف المؤرخ محمّل':'الأسعار المتاحة')+'</div><form id="performanceDateForm" class="'+(datesOpen?'':'hidden ')+'space-y-2 border border-slate-800 rounded-xl p-3"><div class="grid grid-cols-2 gap-2 text-xs"><label>إغلاق بداية الفترة<input name="from" type="date" required value="'+r.start+'" max="'+r.end+'" class="'+field+'"></label><label>إغلاق نهاية الفترة<input name="to" type="date" required value="'+r.end+'" max="'+market.session_date+'" class="'+field+'"></label></div><button type="submit" class="bg-indigo-600 text-white text-xs font-bold rounded-xl px-3 py-2 active:scale-95">تطبيق الفترة وحساب الأداء</button><p data-period-error role="alert" class="text-xs text-rose-400"></p></form>');
 root.querySelectorAll('.perf-preset-btn').forEach(b=>{const code=b.dataset.legacyClick.match(/'([^']+)'/)[1],active=r.preset===code;b.setAttribute('aria-pressed',String(active));b.className='perf-preset-btn px-2.5 py-1 rounded-lg text-xs font-bold border transition shrink-0 active:scale-95 '+(active?'bg-indigo-600 text-white shadow border-indigo-500':'bg-slate-800 text-slate-300 border-slate-700 hover:text-white');});
 for(const [id,v]of Object.entries({perf_kpi_current_val:r.ending.totalWealth,perf_kpi_total_cost:r.beginning.totalWealth,perf_kpi_pnl_egp:r.net,perf_gross_pnl:r.gross,perf_paid_fees:r.fees,perf_net_pnl:r.net,perf_realized_pnl:r.realized,perf_unrealized_pnl:r.unrealizedChange}))money(root,id,v);
 label(root,'perf_kpi_current_val','القيمة في نهاية الفترة');label(root,'perf_kpi_total_cost','القيمة في بداية الفترة');label(root,'perf_kpi_pnl_egp','صافي نتيجة الفترة (بعد الرسوم)');label(root,'perf_kpi_return_pct','عائد الفترة (Modified Dietz)');label(root,'perf_unrealized_pnl','تغير الأرباح غير المحققة');
 L.put(root,'perf_kpi_return_pct',pc(r.returnPct));L.put(root,'perfBenchPortfolio',pc(r.returnPct));L.put(root,'perfBenchEgx33',pc(r.benchmark));L.put(root,'perfBenchCbe','غير متاح');L.put(root,'perfAlphaBadge',r.returnPct!=null&&r.benchmark!=null?'فرق العائد: '+pc(r.returnPct-r.benchmark):'تحتاج حدود الفترة المكتملة');
 for(const[type,prefix]of [['stock','stocks'],['fund','funds'],['gold','gold']]){const g=r.groups[type];money(root,'perf_'+prefix+'_pnl_egp',g.profit);money(root,'perf_'+prefix+'_val',g.value);L.put(root,'perf_'+prefix+'_return_pct','نتيجة الفترة');const title=L.by(root,'perf_'+prefix+'_pnl_egp')?.previousElementSibling?.querySelector('span:last-child');if(title)title.textContent=({stock:'الأسهم',fund:'الصناديق',gold:'الذهب'}[type])+' ('+g.count+')';}
 const headers=root.querySelectorAll('table thead th');['الأصل','الكمية في النهاية','قيمة البداية','قيمة النهاية','نتيجة الأصل في الفترة','تاريخ السعر'].forEach((t,i)=>{if(headers[i])headers[i].textContent=t;});
 L.html(root,'perfHoldingsDetailedTableBody',r.rows.map(h=>'<tr class="border-b border-slate-800/60"><td class="p-2 font-bold">'+e(h.ticker)+'</td><td class="p-2 text-center font-mono">'+n(h.qty,4)+'</td><td class="p-2 text-center font-mono">'+n(h.startValue)+'</td><td class="p-2 text-center font-mono">'+n(h.endValue)+'</td><td class="p-2 text-center font-mono '+(h.profit==null?'text-slate-400':h.profit>=0?'text-emerald-400':'text-rose-400')+'">'+n(h.profit)+'</td><td class="p-2 text-left font-mono text-[10px]" title="'+e(h.source||'السعر غير متاح')+'">'+e(h.quoteDate||'غير متاح')+'</td></tr>').join('')||'<tr><td colspan="6" class="p-3 text-slate-400">لا توجد أصول في الفترة المختارة.</td></tr>');
 L.html(root,'perfBestWorstContainer',[...r.rows].sort((a,b)=>(b.profit??-Infinity)-(a.profit??-Infinity)).map(h=>'<div class="flex justify-between text-xs"><b class="font-mono">'+e(h.ticker)+'</b><span class="font-mono '+(h.profit>=0?'text-emerald-400':'text-rose-400')+'">'+n(h.profit)+' ج</span></div>').join('')||'<p class="text-xs text-slate-400">لا يوجد ترتيب لأصول هذه الفترة.</p>');
 const pill=root.querySelector('.text-\[10px\].bg-slate-800');if(pill)pill.textContent='دفتر العمليات المؤرخ';
 root.insertAdjacentHTML('beforeend',L.section('التدفقات وجودة تقييم الفترة','<div class="grid grid-cols-2 gap-2 text-xs"><span>صافي الإيداعات والسحوبات والأرصدة المضافة</span><b class="font-mono">'+n(r.externalFlows)+' ج</b><span>التوزيعات النقدية المسجلة</span><b class="font-mono">'+n(r.income)+' ج</b></div><p class="text-[11px] text-slate-400">صافي النتيجة = قيمة النهاية − قيمة البداية − التدفقات الخارجية. العمليات محسوبة بعد إغلاق البداية وحتى إغلاق النهاية. العائد يستخدم Modified Dietz بترجيح تاريخ التدفقات، وليس عائداً سنوياً.</p>'+(r.complete?'':'<p class="text-xs text-amber-300">التقييم غير مكتمل: '+e(r.beginning.missing.map(t=>t+' عند البداية').concat(r.ending.missing.map(t=>t+' عند النهاية')).join('، ')||'الرصيد النقدي غير موثق')+'. لا تُستخدم أسعار اليوم لتقييم تاريخ قديم.</p>')+(r.unknownFees?'<p class="text-xs text-amber-300">'+r.unknownFees+' عملية برسوم غير معلومة؛ النتيجة تقدير على الرسوم المسجلة فقط.</p>':'')+'<p class="text-[10px] text-slate-400">كل أصل يعرض آخر سعر موثق لا يتجاوز تاريخ التقييم. قد تختلف تواريخ أسعار الصناديق؛ الملف المرجعي لا يثبت NAV لحظياً.'+(r.benchmarkDates.length?' تاريخا مؤشر EGX33: '+r.benchmarkDates.join(' / '):'')+'</p>'+(loadError?'<p class="text-xs text-amber-300">'+e(loadError)+'</p>':'')+'<div class="flex gap-2 flex-wrap"><button data-performance-export class="bg-slate-800 text-sky-300 px-3 py-2 text-xs rounded-xl">تصدير الفترة CSV</button><button data-performance-print class="bg-slate-800 text-slate-300 px-3 py-2 text-xs rounded-xl">حفظ PDF / طباعة</button><button data-performance-ai class="bg-indigo-600 text-white px-3 py-2 text-xs rounded-xl">مناقشة الأداء مع Gemini</button><button data-action="add" class="bg-emerald-600 text-white px-3 py-2 text-xs rounded-xl">تسجيل عملية</button></div>'));
 root.insertAdjacentHTML('beforeend',L.section('مسار نتيجة الفترة','<canvas id="performancePeriodChart" height="170" aria-label="صافي نتيجة الفترة بعد التدفقات"></canvas><p class="text-[10px] text-slate-400">يعرض التقييمات التي تسمح بها الأسعار المؤرخة؛ لا يصل الخط عبر تقييم ناقص.</p>'));
 return root.outerHTML;
}
async function load(){if(loaded||loading)return;loading=true;try{const response=await fetch('daily-reports/index.json',{cache:'no-store'});if(!response.ok)throw Error('تعذر تحميل فهرس الأسعار التاريخية');const index=await response.json();const settled=await Promise.allSettled(index.reports.filter(m=>m.audited&&/^daily-reports\/\d{4}-\d{2}-\d{2}\.json$/.test(m.file)).map(async meta=>{const response=await fetch(meta.file);if(!response.ok)throw Error('أرشيف ناقص '+meta.date);const r=await response.json();if(r.date!==meta.date||r.generated_from?.commit!==meta.source_commit)throw Error('مصدر الأرشيف لا يطابق الفهرس');return r;}));reports=settled.filter(x=>x.status==='fulfilled').map(x=>x.value);if(settled.some(x=>x.status==='rejected'))loadError='بعض الملفات التاريخية غير متاحة؛ عُرضت البيانات التي اجتازت التحقق فقط.';loaded=true;}catch(error){loadError=error.message;loaded=true;}finally{loading=false;if(route==='performance')render();}}
function draw(){const canvas=$('performancePeriodChart');if(!canvas||!result||!window.Chart)return;new Chart(canvas,{type:'line',data:{labels:result.points.map(x=>x.date),datasets:[{label:'نتيجة الفترة بعد التدفقات',data:result.points.map(x=>x.profit),borderColor:'#6366f1',backgroundColor:'rgba(99,102,241,.12)',fill:true,tension:.15,spanGaps:false}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{x:{ticks:{font:{family:'JetBrains Mono',size:9},color:'#94a3b8'},grid:{color:'rgba(148,163,184,.08)'}},y:{ticks:{font:{family:'JetBrains Mono',size:10},color:'#94a3b8'},grid:{color:'rgba(148,163,184,.08)'}}}}});}
const previousRun=LegacyActions.run;LegacyActions.run=function(call,name,args,el){if(name==='setPerformancePeriodPreset'){presetCode=args[0];range=null;datesOpen=false;render();return true;}if(name==='openPeriodPerformanceModal'){datesOpen=!datesOpen;render();$('performanceDateForm')?.querySelector('input')?.focus();return true;}return previousRun(call,name,args,el);};
document.addEventListener('submit',ev=>{if(ev.target.id!=='performanceDateForm')return;ev.preventDefault();const data=new FormData(ev.target),next={start:data.get('from'),end:data.get('to'),preset:'CUSTOM'};try{P.calculate(state,market,next,reports);range=next;presetCode='CUSTOM';render();}catch(error){ev.target.querySelector('[data-period-error]').textContent=error.message;}});
function csvRows(){if(!result)return null;return [['الفترة',result.start,result.end],['صافي النتيجة',result.net],['قيمة البداية',result.beginning.totalWealth],['قيمة النهاية',result.ending.totalWealth],['التدفقات الخارجية',result.externalFlows],['رسوم الفترة',result.fees],['الرسوم المجهولة',result.unknownFees],['Modified Dietz %',result.returnPct],['الأصل','كمية النهاية','قيمة البداية','قيمة النهاية','نتيجة الفترة','تاريخ السعر','المصدر'],...result.rows.map(h=>[h.ticker,h.qty,h.startValue,h.endValue,h.profit,h.quoteDate,h.source])];}
document.addEventListener('click',ev=>{if(ev.target.closest('[data-performance-export]'))download('performance-'+result.start+'-'+result.end+'.csv',C.csv(csvRows()),'text/csv;charset=utf-8');if(ev.target.closest('[data-performance-print]'))window.print();if(ev.target.closest('[data-performance-ai]'))AIAdvisor.open({kind:'performance',question:'اشرح لي طريقة حساب الأداء في الفترة المختارة وما البيانات الناقصة فيها.',performance:{start:result.start,end:result.end,complete:result.complete,missingStart:result.beginning.missing,missingEnd:result.ending.missing,unknownFees:result.unknownFees,method:result.returnMethod}});});
performanceView=renderPerformance;const oldRender=render;render=function(){oldRender();if(route==='performance'){draw();load();}};window.PerformanceUI={result:()=>result,csvRows,reload:()=>{loaded=false;load();},status:()=>({loaded,loading,reports:reports.length,loadError})};render();
})();
