(function(root){'use strict';
const Calendar=typeof module==='object'&&module.exports?require('./market-calendar'):root.MarketCalendar;
const finite=v=>typeof v==='number'&&Number.isFinite(v),round=v=>finite(v)?Number(v.toFixed(2)):null,pct=(a,b)=>finite(a)&&finite(b)&&b>0?round((a/b-1)*100):null;
function week(date){const d=new Date(date+'T12:00:00Z');return Calendar.add(date,-d.getUTCDay());}
function monthEnd(month){return new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),0,12)).toISOString().slice(0,10);}
function aggregate(input,kind,start,end,calendar,today=Calendar.cairoDate(),weeks=[]){
 if(!['weekly','monthly'].includes(kind)||!Calendar.valid(start)||!Calendar.valid(end)||start>end)throw Error('فترة التقرير غير صالحة');
 const byDate=new Map();for(const r of input){if(!r?.audit?.audited||r.date<start||r.date>end||r.date>today||r.report_type==='non_trading_day'||r.report_type==='pending_session')continue;if(byDate.has(r.date)&&JSON.stringify(byDate.get(r.date))!==JSON.stringify(r))throw Error('تقرير يوم مكرر بقيم مختلفة');byDate.set(r.date,r);}
 const dates=Calendar.sessions(calendar,start,end<today?end:today),reports=[...byDate.values()].sort((a,b)=>a.date.localeCompare(b.date)),missing=dates.filter(d=>!byDate.has(d)),partial=reports.filter(r=>!r.coverage?.source_complete).map(r=>r.date),first=dates[0],last=dates.at(-1),stocks={},indices={},funds=[];
 const symbols=[...new Set(reports.flatMap(r=>Object.keys(r.stocks||{})))];
 for(const ticker of symbols){
  const qs=reports.filter(r=>r.stocks?.[ticker]).map(r=>({date:r.date,q:r.stocks[ticker]})),a=qs[0],z=qs.at(-1),endpoint=a.date===first&&z.date===last,broken=qs.some(x=>x.q.basis_discontinuity),all=qs.length===dates.length&&missing.length===0,volumeComplete=all&&qs.every(x=>finite(x.q.volume)),ohlcComplete=all&&qs.every(x=>x.q.ohlc_valid);
  const close=z.date===last?z.q.close:null,actions=z.q.split_basis?.actions||[],verifiedBasis=broken&&endpoint&&qs.filter(x=>x.q.basis_discontinuity).every(x=>x.q.split_basis?.source&&x.q.corporate_actions?.length)&&actions.every(x=>Calendar.valid(x.date)&&finite(x.ratio)&&x.ratio>0),factor=d=>verifiedBasis?actions.filter(x=>x.date>d&&x.date<=z.date).reduce((v,x)=>v*x.ratio,1):1,previous=endpoint&&finite(a.q.previous_close)?a.q.previous_close/factor(a.date):null,hlComplete=all&&qs.every(x=>finite(x.q.high)&&finite(x.q.low));
  stocks[ticker]={...z.q,ticker,close,previous_close:previous,period_start_price:previous,period_last_price:z.q.close,session_date:z.date,open:ohlcComplete?a.q.open/factor(a.date):null,high:hlComplete?Math.max(...qs.map(x=>x.q.high/factor(x.date))):null,low:hlComplete?Math.min(...qs.map(x=>x.q.low/factor(x.date))):null,volume:volumeComplete?qs.reduce((s,x)=>s+x.q.volume,0):null,value_traded:all&&qs.every(x=>finite(x.q.value_traded))?qs.reduce((s,x)=>s+x.q.value_traded,0):null,known_volume:qs.reduce((s,x)=>s+(finite(x.q.volume)?x.q.volume:0),0),volume_sessions:qs.filter(x=>finite(x.q.volume)).length,change_pct:endpoint&&(!broken||verifiedBasis)?pct(close,previous):null,observed_start_date:a.date,observed_start_price:a.q.close,observed_change_pct:broken&&!verifiedBasis?null:pct(z.q.close,a.q.close/factor(a.date)),reported_change_pct:null,basis_discontinuity:broken,rsi:broken&&!verifiedBasis?null:z.q.rsi,sma20:broken&&!verifiedBasis?null:z.q.sma20,sma50:broken&&!verifiedBasis?null:z.q.sma50,sma200:broken&&!verifiedBasis?null:z.q.sma200,ohlc_valid:ohlcComplete,observed_sessions:qs.length,period_basis_verified:verifiedBasis,change_basis:verifiedBasis?'declared_split_adjusted_period_endpoints':broken?'unadjusted_period_basis':'period_endpoints',analysis:{state:verifiedBasis?'ملخص الفترة المعدل بعدد الأسهم':broken?'أساس السعر يحتاج تعديلًا':!endpoint?'تغطية جزئية':'ملخص الفترة',text:verifiedBasis?'عائد السعر للفترة معدل بإجراءات عدد الأسهم المعلنة في المصدر، ولا يغيّر كميات دفتر العمليات.':broken?'لم تُحسب نسبة الفترة لأن السلسلة تغير أساس سعرها؛ لا يُستخدم التغير المعدل ليوم واحد لتعديل تاريخ كامل.':'التغير من الإغلاق السابق لأول جلسة إلى إغلاق آخر جلسة، والحجم مجموع الأحجام اليومية المتاحة مرة واحدة.',support:null,resistance:null}};
 }
 for(const code of [...new Set(reports.flatMap(r=>Object.keys(r.indices||{})))]){const qs=reports.filter(r=>r.indices?.[code]).map(r=>({date:r.date,q:r.indices[code]})),a=qs[0],z=qs.at(-1),endpoint=a.date===first&&z.date===last;indices[code]={...z.q,close:z.date===last?z.q.close:null,previous_close:endpoint?a.q.previous_close:null,change_pct:endpoint?pct(z.q.close,a.q.previous_close):null,open:a.date===first?a.q.open:null,session_date:z.date,observed_sessions:qs.length};}
 for(const code of [...new Set(reports.flatMap(r=>(r.funds||[]).map(q=>q.code)))]){const qs=reports.map(r=>({date:r.date,q:r.funds?.find(q=>q.code===code)})).filter(x=>x.q),a=qs[0],z=qs.at(-1),endpoint=a.date===first&&a.q.session_date<=first&&z.date===last&&z.q.session_date===last,base=a.q.session_date<first?a.q.price:a.q.previous_close,baseDate=a.q.session_date<first?a.q.session_date:a.q.previous_session_date;funds.push({...z.q,previous_close:endpoint?base:null,previous_session_date:endpoint?baseDate:null,change_pct:endpoint?pct(z.q.price,base):null,reported_change_pct:null,observed_sessions:qs.length});}
 const fx_gold={};for(const key of Object.keys(reports.at(-1)?.fx_gold||{})){const firstQuote=reports[0]?.fx_gold?.[key],lastQuote=reports.at(-1).fx_gold[key],base=firstQuote?.session_date<start?firstQuote.close:firstQuote?.previous_close,baseDate=firstQuote?.session_date<start?firstQuote.session_date:firstQuote?.previous_session_date,valid=Calendar.valid(baseDate)&&baseDate<start&&lastQuote.session_date<=end;fx_gold[key]={...lastQuote,previous_close:valid?base:null,previous_session_date:valid?baseDate:null,chgPct:valid?pct(lastQuote.close,base):null,comparison_kind:'period endpoints'};}
 const moves=Object.values(stocks).filter(q=>finite(q.change_pct)).sort((a,b)=>b.change_pct-a.change_pct),g=moves.filter(q=>q.change_pct>0),l=moves.filter(q=>q.change_pct<0),idx=Object.values(indices).map(q=>q.change_pct).filter(finite),avg=idx.length?round(idx.reduce((s,q)=>s+q,0)/idx.length):null;
 const label=kind==='weekly'?'الأسبوعي':'الشهري',id=kind==='weekly'?start:start.slice(0,7),covered=reports.length,complete=missing.length===0&&partial.length===0&&dates.length>0,notes=['أعدّ Codex هذا الملخص من التقارير اليومية المراجعة، والتقرير الشهري من أيام التقارير الأسبوعية دون تكرار.','الأسبوع التداولي للبورصة المصرية في هذا النظام هو الأحد إلى الخميس؛ الجمعة والسبت لا يدخلان في التقرير الأسبوعي.','عائد الفترة = إغلاق آخر جلسة ÷ الإغلاق السابق لأول جلسة − 1. لا تُجمع النسب اليومية أو الأسبوعية.','الأحجام تجمع مرة واحدة لكل يوم؛ الحجم الكلي غير متاح إن نقص يوم أو رقم. لا تجمع قيم RSI أو أسعار الأسهم أو معدلات العائد السنوي.'];
 if(missing.length)notes.push('جلسات بلا تقرير: '+missing.join('، '));
 if(partial.length)notes.push('تقارير بتغطية مصدر جزئية: '+partial.join('، '));
 if(Object.values(stocks).some(q=>q.basis_discontinuity&&!q.period_basis_verified))notes.push('حُجبت عوائد الفترة للأصول ذات تغير أساس السعر حتى توفر سلسلة معدلة موثقة.');
 return {schema:4,generated_at:new Date().toISOString(),id,kind,date:end,period_start:start,period_end:end,period_final:end<=today,report_type:kind+'_summary',sessionDay:kind==='weekly'?'الأسبوع':'الشهر',status:complete?'ملخص الفترة — تغطية الجلسات مكتملة':'ملخص الفترة — تغطية جزئية',title:'التقرير '+label+' الشامل — '+start+' إلى '+end,subtitle:covered+' تقريرًا يوميًا من '+dates.length+' جلسة متوقعة حتى '+(end<today?end:today),prepared_by:'Codex',generated_from:{repository:'Maherelkhateeb/egypt-investment-workspace',file:'daily-reports/index.json',snapshot_updated_at:new Date().toISOString()},components:reports.map(r=>({date:r.date,file:'daily-reports/'+r.date+'.json'})),component_weeks:weeks,coverage:{expected_sessions:dates,covered_sessions:reports.map(r=>r.date),missing_sessions:missing,partial_sessions:partial,complete},audit:{audited:true,review_version:4,policy:'تجميع زمني بلا تكرار؛ المقارنات الناقصة لا تُستبدل بصفر.',notes},session_analysis:{headline:'ملخص '+label+' — '+covered+' جلسات موثقة',nature:g.length+' أصلًا مرتفعًا و'+l.length+' منخفضًا و'+(Object.keys(stocks).length-moves.length)+' دون مقارنة مكتملة للفترة. '+(complete?'التغطية اليومية مكتملة.':'تظهر حدود التغطية في سجل التدقيق.'),liquidity:'الأحجام المجمعة من بيانات الأيام؛ لا توجد بيانات موثقة لصافي تدفقات فئات المستثمرين.',tomorrow:'الموعد المعتاد التالي بعد نهاية الفترة: '+Calendar.nextSession(calendar,end)},stocks,indices,funds,fx_gold,portfolio_analysis:Object.values(stocks),market_summary:{stocks_with_change:moves.length,stocks_without_change:Object.keys(stocks).length-moves.length,gainers:g.length,losers:l.length,flat:moves.length-g.length-l.length,known_volume:Object.values(stocks).reduce((v,q)=>v+(q.volume||0),0),volume_assets:Object.values(stocks).filter(q=>finite(q.volume)).length,known_turnover:Object.values(stocks).reduce((v,q)=>v+(q.value_traded||0),0),turnover_assets:Object.values(stocks).filter(q=>finite(q.value_traded)).length,top_gainers:g.slice(0,5),top_losers:l.slice(-5).reverse(),index_bias:avg===null?'غير محسوم':avg>.35?'إيجابي':avg<-.35?'سلبي':'متوازن',average_index_change:avg},sources:reports.flatMap(r=>[{date:r.date,commit:r.generated_from?.commit,file:'daily-reports/'+r.date+'.json'}]),disclaimer:'ملخص معلوماتي، مع حدود مصادره، وليس توصية استثمارية.'};
}
function fromWeeks(weeks,lookup,start,end,calendar,today){const files=new Map();for(const w of weeks)for(const c of w.components||[])if(c.date>=start&&c.date<=end){if(files.has(c.date)&&files.get(c.date)!==c.file)throw Error('مرجع يوم مكرر');files.set(c.date,c.file);}const reports=[...files].map(([d,f])=>{const r=lookup(f);if(!r||r.date!==d)throw Error('تقرير يوم غير مطابق لمرجعه الأسبوعي');return r;});return aggregate(reports,'monthly',start,end,calendar,today,weeks.filter(w=>(w.components||[]).some(c=>c.date>=start&&c.date<=end)).map(w=>({id:w.id,start:w.period_start,end:w.period_end})));}
const api={week,monthEnd,aggregate,fromWeeks};if(typeof module==='object'&&module.exports)module.exports=api;else root.ReportPeriods=api;
})(typeof globalThis==='object'?globalThis:this);
