/* Deterministic whole-application checks. AI may propose only listed reversible repairs. */
(function(root){'use strict';
const C=typeof module==='object'&&module.exports?require('./core.js'):root.InvestCore;
const repairIds=['refresh_market','reset_view_preferences','close_duplicate_dialogs','rebind_controls'];
function inspect(input,observation={}){const findings=[],add=(id,area,status,detail,repair=null)=>findings.push({id,area,status,detail,repair});let state,market;
try{state=C.validateState(input.state);add('ledger_valid','accounting','pass','دفتر العمليات اجتاز التحقق من الصيغة، التكرار، الأرصدة والبيع فوق الحيازة');}catch(err){add('ledger_valid','accounting','error',err.message);}
try{market=C.validateMarket(input.market);add('market_valid','data','pass','الأسعار وتواريخ الجلسات والإغلاق السابق ومصادرها اجتازت التحقق');}catch(err){add('market_valid','data','error',err.message,'refresh_market');}
if(state&&market){const p=C.portfolio(state,market);add('valuation_complete','accounting',p.complete?'pass':'warning',p.complete?'تتوفر أسعار جميع الحيازات':'أسعار ناقصة: '+p.missing.join('، '));add('fees_complete','accounting',p.feesComplete?'pass':'warning',p.unknownFees+' عملية برسوم غير معلومة');add('cash_complete','accounting',p.cashKnown?'pass':'warning',p.cashKnown?'الرصيد النقدي موثق في السجل':'الرصيد النقدي المستورد غير موثق');const sum=p.positions.reduce((a,h)=>a+(h.value??0),0);add('positions_total','accounting',Math.abs(sum-p.value)<.000001?'pass':'error','مطابقة مجموع تقييمات الأصول لإجمالي الحيازات');const f=C.freshness(market,Date.now(),input.calendar);add('market_freshness','data',f.old||f.future?'warning':'pass','جلسة '+market.session_date+(f.future?'؛ وقت الجلب في المستقبل':f.old?'؛ لقطة تحتاج تحديثاً':''),f.old?'refresh_market':null);for(const [symbol,q]of Object.entries(market.assets)){if(q.status==='unverified'||(q.type==='fund'&&!(q.status==='verified'&&q.nav_verified===true)))add('source_'+symbol,'data','warning','سعر '+symbol+(q.type==='fund'?' لا يثبت NAV معتمداً من ناشر الصندوق؛ لقطة الوسيط تختلف عن اعتماد الناشر':' غير متحقق في المصدر'));}}
if(state&&market){const p=C.portfolio(state,market);if(p.complete&&p.cashKnown){const reconciliation=p.totalWealth-state.openingCash-p.openingValue-p.deposits+p.withdrawals;add('profit_cash_reconciliation','accounting',Math.abs(reconciliation-p.net)<.00001?'pass':'error','مطابقة صافي الربح مع تغير الثروة بعد تدفقات رأس المال؛ لا خصم مكرر للرسوم');}for(const [symbol,h]of Object.entries(state.histories)){try{if(!/^https:\/\//.test(h.source||''))throw Error('مصدر السلسلة غير موثق');C.indicators(h.candles);add('history_'+symbol,'data','pass','سلسلة '+symbol+' اجتازت التواريخ وتوازن OHLC');}catch(err){add('history_'+symbol,'data','error','سلسلة '+symbol+': '+err.message);}}for(const [symbol,r]of Object.entries(state.research)){const source=/^https:\/\//.test(r.source||'')&&Boolean(r.published);add('research_'+symbol,'data',source?'pass':'warning','بحث '+symbol+(source?' له مصدر وتاريخ مدخلان؛ لم يراجع المستند مستقلاً':' يحتاج مستنداً وتاريخاً للتحليل المالي'));}const positions=p.positions.filter(h=>h.assetType==='stock'),unverified=positions.filter(h=>!market.assets[h.ticker]?.sharia_source_url||!market.assets[h.ticker]?.sharia_checked_at);add('sharia_evidence','data',unverified.length?'warning':'pass',unverified.length?'أصول تحتاج مستند تصنيف شرعي مؤرخ: '+unverified.map(h=>h.ticker).join('، '):'لا توجد حيازات أسهم بلا مستند في نطاق الفحص');}
if(market){const f=C.freshness(market,Date.now(),input.calendar);for(const q of f.assets)if(q.stale||q.future)add('quote_date_'+q.symbol,'data','warning','سعر '+q.symbol+' مؤرخ '+q.date+(q.future?'؛ تاريخ مستقبلي':'؛ أقدم من آخر جلسة متوقعة '+f.expectedSession)+(q.type==='fund'?'؛ يراجع جدول نشر NAV لدى الصندوق':''));}
const items=input.news?.items||[],urls=new Set();let duplicate=0,bad=0;for(const item of items){try{const url=new URL(item.url);if(url.protocol!=='https:')bad++;if(urls.has(url.href))duplicate++;urls.add(url.href);}catch{bad++;}}add('news_links','data',bad?'error':'pass',bad?'روابط غير صالحة: '+bad:'روابط الأخبار تستخدم HTTPS');add('news_duplicates','data',duplicate?'warning':'pass','أخبار مكررة: '+duplicate);add('news_available','data',input.news?.error?'warning':'pass',input.news?.error?'تعذر تحديث مصدر الأخبار':items.length+' عنواناً في النشرة');
if(observation.ids){const counts={};for(const id of observation.ids)counts[id]=(counts[id]||0)+1;const repeated=Object.entries(counts).filter(([,n])=>n>1).map(([id])=>id);add('dom_ids','interface',repeated.length?'error':'pass',repeated.length?'معرفات مكررة: '+repeated.join(', '):'معرفات عناصر الواجهة فريدة',repeated.length?'close_duplicate_dialogs':null);}
if(observation.controls){const missing=observation.controls.filter(c=>!c.bound);add('control_bindings','interface',missing.length?'error':'pass',missing.length?'إجراءات غير مربوطة: '+missing.map(c=>c.label||c.call).join('، '):observation.controls.length+' إجراء واجهة له معالج محدد',missing.length?'rebind_controls':null);}
if(observation.runtimeErrors)add('runtime_errors','interface',observation.runtimeErrors.length?'error':'pass',observation.runtimeErrors.length?observation.runtimeErrors.slice(-5).join('، '):'لم تُلتقط أخطاء تشغيل في هذه الجلسة');
if(observation.modules)for(const m of observation.modules)add('module_'+m.name,'interface',m.ok?'pass':'error',m.name+(m.ok?' محمل ومتصل':' غير متاح'));
if(observation.assets)for(const a of observation.assets)add('asset_'+a.name,'interface',a.ok?'pass':'error',a.name+(a.ok?' متاح':' تعذر تحميله'));
if(observation.archives)for(const a of observation.archives)add('archive_'+a.date,'data',a.ok?'pass':'error',a.date+(a.ok?' يطابق ملفه المؤرخ':' لا يطابق تاريخ الملف أو تعذر تحميله'));
const summary={checks:findings.length,passed:findings.filter(x=>x.status==='pass').length,warnings:findings.filter(x=>x.status==='warning').length,errors:findings.filter(x=>x.status==='error').length};return {at:new Date().toISOString(),summary,findings,scope:'فحوص محددة للواجهة والملفات ومصادر البيانات ودفتر الحسابات؛ ليست ضماناً لاكتشاف كل عطل ممكن'};}
function validatePlan(plan,report){if(!Array.isArray(plan)||plan.length>20)throw Error('خطة الإصلاح غير صالحة');const seen=new Set();return plan.map(p=>{const f=report.findings.find(x=>x.id===p.findingId&&x.status!=='pass');if(!f||!repairIds.includes(p.actionId)||p.actionId!==f.repair||seen.has(p.findingId))throw Error('اقتراح إصلاح خارج نطاق الفحص');seen.add(p.findingId);return {findingId:p.findingId,actionId:p.actionId,explanation:String(p.explanation||'').slice(0,700)};});}
const api={inspect,validatePlan,repairIds};if(typeof module==='object'&&module.exports)module.exports=api;else root.SystemAudit=api;
})(typeof globalThis==='object'?globalThis:this);
