import Calendar from '../market-calendar.js';
export const finite=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
export const round=(v,n=2)=>finite(v)?Number(Number(v).toFixed(n)):null;
export const pct=(a,b)=>finite(a)&&finite(b)&&Number(b)>0?round((Number(a)/Number(b)-1)*100):null;
const focus=['ORHD','ADIB','TMGH','OCDI','EGAL','EFID','ETEL','EFIH'];
const dayName=date=>new Intl.DateTimeFormat('ar-EG',{timeZone:'Africa/Cairo',weekday:'long'}).format(new Date(date+'T12:00:00Z'));
function summary(stocks,indices){const ranked=Object.values(stocks).filter(q=>finite(q.change_pct)).sort((a,b)=>b.change_pct-a.change_pct),g=ranked.filter(q=>q.change_pct>0),l=ranked.filter(q=>q.change_pct<0),moves=Object.values(indices).map(q=>q.change_pct).filter(finite),avg=moves.length?round(moves.reduce((a,b)=>a+b,0)/moves.length):null;return {stocks_with_change:ranked.length,stocks_without_change:Object.keys(stocks).length-ranked.length,gainers:g.length,losers:l.length,flat:ranked.length-g.length-l.length,best:ranked[0]||null,worst:ranked.at(-1)||null,top_gainers:g.slice(0,5),top_losers:l.slice(-5).reverse(),average_index_change:avg,index_bias:avg===null?'غير محسوم':avg>.35?'إيجابي':avg<-.35?'سلبي':'متوازن'};}
function reading(q){const valid=finite(q.high)&&finite(q.low)&&finite(q.close),pivot=valid?round((q.high+q.low+q.close)/3,5):null,rs=valid?[round(2*pivot-q.high,5),round(2*pivot-q.low,5)]:[null,null],s=rs[0]<q.close?rs[0]:null,r=rs[1]>q.close?rs[1]:null;return {state:q.change_pct===null?'مقارنة غير مكتملة':q.change_pct>0?'إغلاق مرتفع':q.change_pct<0?'إغلاق منخفض':'دون تغير',tone:q.change_pct>0?'positive':q.change_pct<0?'negative':'watch',text:valid?'Classic Pivot من أعلى وأدنى وإغلاق الجلسة؛ مستويات مرجعية للجلسة التالية، والمسافة محسوبة من سعر الإغلاق الحالي.':'لا تتوفر شمعة متسقة لحساب Classic Pivot؛ لا يولّد التقرير دعماً أو مقاومة من بيانات ناقصة.',pivot,support:s,resistance:r,support_distance_pct:pct(s,q.close),resistance_distance_pct:pct(r,q.close)};}
export function reviewSnapshot(date,source,previous,market,calendar){
 if(!Calendar.valid(date)||Calendar.cairoDate(new Date(source.snapshot.updated_at))!==date)throw Error('تاريخ لقطة المصدر لا يطابق '+date);
 if(Calendar.status(calendar,date).state==='OFFICIAL_HOLIDAY')throw Error('رفض إنشاء إغلاق في إجازة البورصة '+date);
 const data=source.snapshot,issues=[],stocks={},indices={},funds=[],fx_gold={};
 const priorIsSession=previous&&Calendar.sessions(calendar,Calendar.add(previous.date,1),date).join()===date;
 for(const [ticker,raw]of Object.entries(data.stocks||{})){
  const verified=market.assets?.[ticker],own=verified?.session_date===date&&verified.status==='user_verified_snapshot'?verified:null;
  const q={ticker,name:raw.name||own?.name||ticker,session_date:date,close:round(own?.close??raw.close,5),open:round(raw.open,5),high:round(raw.high,5),low:round(raw.low,5),volume:finite(raw.volume)&&Number(raw.volume)>=0?Number(raw.volume):null,rsi:finite(raw.rsi)&&raw.rsi>=0&&raw.rsi<=100?round(raw.rsi,1):null,sma20:round(raw.sma20),sma50:round(raw.sma50),sma200:round(raw.sma200),value_traded:round(raw.value_traded),source:own?.source_url||raw.source||null,verification:own?'user_verified_snapshot':'archived_provider_snapshot',reported_change_pct:round(raw.chg),previous_close:null,previous_session_date:null,change_pct:null,change_basis:'missing_previous_close'};
  if(q.close===null||q.close<=0){issues.push({ticker,code:'invalid_close'});continue;}
  let prev=priorIsSession?previous.stocks?.[ticker]?.close:null;
  if(own&&finite(own.previous_close)&&own.previous_session_date<date){prev=own.previous_close;q.previous_session_date=own.previous_session_date;}
  q.previous_close=round(prev,5);q.previous_session_date??=finite(prev)?previous.date:null;q.previous_close_source=own?.source_url||previous?.generated_from?.commit||null;
  if(own&&priorIsSession&&finite(previous.stocks?.[ticker]?.close)&&Math.abs(previous.stocks[ticker].close-prev)>.00001)issues.push({ticker,code:'previous_reference_difference',archived:previous.stocks[ticker].close,chosen:prev});
  const unadjusted=priorIsSession?pct(q.close,previous.stocks?.[ticker]?.close):null;
  q.basis_discontinuity=finite(unadjusted)&&Math.abs(unadjusted)>30;
  if(q.basis_discontinuity){issues.push({ticker,code:'price_basis_discontinuity',reported_change:q.reported_change_pct,raw_comparison:unadjusted});q.rsi=q.sma20=q.sma50=q.sma200=null;}
  if(finite(prev)&&(!q.basis_discontinuity||own)){q.change_pct=pct(q.close,prev);q.change_basis=q.basis_discontinuity?'adjusted_user_verified_comparison':'dated_closes';}
  if(finite(q.reported_change_pct)&&finite(q.change_pct)&&Math.abs(q.reported_change_pct-q.change_pct)>.05)issues.push({ticker,code:'reported_change_mismatch',reported:q.reported_change_pct,recalculated:q.change_pct});
  const ohlc=[q.open,q.high,q.low,q.close];q.ohlc_valid=ohlc.every(v=>finite(v)&&v>0)&&q.high+1e-9>=Math.max(q.open,q.low,q.close)&&q.low-1e-9<=Math.min(q.open,q.close);
  if(!q.ohlc_valid){if(ohlc.slice(0,3).some(finite))issues.push({ticker,code:'inconsistent_ohlc'});q.open=q.high=q.low=null;}
  if(own&&Math.abs(Number(raw.close)-q.close)>.00001)issues.push({ticker,code:'documented_close_override',archived:raw.close,reviewed:q.close});
  q.analysis=reading(q);stocks[ticker]=q;
 }
 const src=data.indices||{},pick=(...k)=>k.map(x=>src[x]).find(Boolean);
 for(const [code,raw]of [['EGX30',pick('EGX30')],['EGX33',pick('EGX33 الشريعة','EGX33')],['EGX70',pick('EGX70 EWI','EGX70')],['EGX100',pick('EGX100 EWI','EGX100')]]){
  if(!raw||!finite(raw.close)||raw.close<=0)continue;
  const own=market.indices?.[code]?.session_date===date?market.indices[code]:null,prev=own?.previous_close??(priorIsSession?previous.indices?.[code]?.close:null),close=round(own?.close??raw.close);
  indices[code]={name:raw.name||code,open:round(raw.open),close,previous_close:round(prev),change_pct:pct(close,prev),reported_change_pct:round(raw.chgPct),session_date:date,source:own?.source_url||raw.source||null};
  if(finite(indices[code].change_pct)&&finite(raw.chgPct)&&Math.abs(indices[code].change_pct-raw.chgPct)>.05)issues.push({ticker:code,code:'reported_change_mismatch',reported:raw.chgPct,recalculated:indices[code].change_pct});
 }
 const rawFunds=Array.isArray(data.funds)?Object.fromEntries(data.funds.map(q=>[q.code,q])):data.funds||{};
 const fundMap=new Map();
 for(const [code,raw]of Object.entries(rawFunds)){
  if(code==='THNDR_GOLD')continue;const q=typeof raw==='object'?raw:{close:raw},price=round(q.price??q.close??q.nav,5),sourceDate=q.last_nav_date||q.session_date||(q.source||'').match(/\d{4}-\d{2}-\d{2}/)?.[0]||null;
  if(price!==null&&price>0)fundMap.set(code,{code,name:q.name||code,price,session_date:sourceDate,reported_change_pct:round(q.chg??q.change_pct),change_pct:null,source:q.source||null,observed_at:data.updated_at});
 }
 for(const [code,q]of Object.entries(market.assets||{}))if(q.type==='fund'&&q.session_date===date&&q.status==='user_verified_snapshot')fundMap.set(code,{code,name:q.name,price:q.close,session_date:q.session_date,source:q.source_url,verification:q.status,change_pct:null,observed_at:data.updated_at});
 for(const f of fundMap.values()){const prior=previous?.funds?.find(x=>x.code===f.code);if(priorIsSession&&f.session_date===date&&prior?.session_date===previous.date){f.previous_close=prior.price;f.previous_session_date=prior.session_date;f.change_pct=pct(f.price,prior.price);}else issues.push({ticker:f.code,code:'nav_comparison_missing_or_stale',nav_date:f.session_date});funds.push(f);}
 for(const [code,raw]of Object.entries(data.fx_gold||{}))if(raw&&typeof raw==='object')fx_gold[code]={...raw,close:round(raw.close,5),chgPct:round(raw.chgPct),session_date:raw.session_date||raw.last_updated_date||null,observed_at:data.updated_at};
 for(const [code,q]of Object.entries(market.assets||{}))if(q.type==='gold'&&q.session_date===date&&q.status==='user_verified_snapshot')fx_gold[code]={name:q.name,close:q.close,previous_close:q.previous_close,chgPct:pct(q.close,q.previous_close),session_date:date,source:q.source_url,unit:'ج / غرام'};
 const s=summary(stocks,indices),invalid=issues.filter(x=>x.code==='inconsistent_ohlc').length,mismatch=issues.filter(x=>x.code==='reported_change_mismatch').length;
 const notes=['أعدّ Codex التقرير وراجع التاريخ وحساب نسب التغير واتساق الشموع ومصادر المقارنة. لا يعني اجتياز الحسابات اعتماد جميع أسعار المزود كسعر رسمي مستقل.','الأسهم ذات مرجع سابق مفقود لا تدخل إحصاء الصعود والهبوط. لا تُحسب نسبة التغير من سعر الافتتاح.','الأسعار المصححة من صور الوسيط تستخدم قيمة المشروع الجديد المؤرخة؛ بقية الأسعار لقطات مزود مؤرشفة مع بيان مصدرها.'];
 if(invalid)notes.push('استُبعدت '+invalid+' شمعة متناقضة؛ قيم الافتتاح والأعلى والأدنى والمستويات الفنية المرتبطة بها أصبحت غير متاحة.');
 if(mismatch)notes.push('رُصدت '+mismatch+' نسبة مزود تختلف عن المقارنة بين الإغلاقات المختارة؛ عُرضت النسبة المعاد حسابها واحتُفظ بالقيمة الأصلية في سجل المراجعة.');
 if(issues.some(x=>x.code==='price_basis_discontinuity'))notes.push('رُصد تغير في أساس سعر أحد الأصول؛ استُبعدت مؤشراته الفنية غير المعدلة، ولا تُنقل المقارنة المعدلة ليوم واحد إلى عائد الأسبوع كله.');
 if(!funds.length)notes.push('لا تحتوي لقطة المصدر على أسعار صناديق؛ لم تُملأ من تاريخ لاحق.');
 const report={schema:4,id:date,kind:'daily',report_type:Object.keys(stocks).length?'reviewed_eod':'historical_partial',date,sessionDay:dayName(date),status:'لقطة إغلاق مؤرخة — مراجعة الحسابات والبيانات',title:'التقرير اليومي الشامل — '+dayName(date)+' '+date,subtitle:'تقرير أعده Codex من المصادر المؤرخة؛ تظهر حدود التغطية والمراجعة',prepared_by:'Codex',generated_from:{repository:'mahereasybakery-web/egypt-sharia-stock-report',commit:source.commit,file:'market_data.json',snapshot_updated_at:data.updated_at},audit:{audited:true,review_version:4,audited_at:new Date().toISOString(),policy:'بيانات مفقودة = غير متاحة؛ لا اختلاق للشموع أو أسعار الصناديق أو تدفقات المستثمرين.',notes,issues},session_analysis:{headline:'جلسة '+dayName(date)+': '+s.index_bias+' للمؤشرات داخل التغطية المتاحة',nature:'داخل المقارنات المؤرخة المتاحة: '+s.gainers+' سهمًا صاعدًا، '+s.losers+' هابطًا، '+s.flat+' دون تغير، و'+s.stocks_without_change+' دون مقارنة مكتملة.',liquidity:'أحجام التداول مأخوذة من لقطة المزود. تدفقات فئات المستثمرين غير متاحة ولا تُستنتج من تغير السعر.',tomorrow:'الموعد المعتاد التالي: '+Calendar.nextSession(calendar,date)+'؛ يراجع التقويم الإجازات الموثقة ولا يفترض بثًا لحظيًا.'},stocks,indices,funds,fx_gold,portfolio_analysis:focus.filter(x=>stocks[x]).map(x=>stocks[x]),market_summary:s,coverage:{stocks:Object.keys(stocks).length,indices:Object.keys(indices).length,funds:funds.length,valid_ohlc:Object.values(stocks).filter(q=>q.ohlc_valid).length,comparisons:s.stocks_with_change,source_complete:Object.keys(stocks).length>0&&Object.keys(indices).length>=2},sources:[...new Set([...Object.values(stocks),...Object.values(indices),...funds].map(q=>q.source).filter(Boolean))],disclaimer:'تحليل معلوماتي تاريخي، مع حدود مصادره، وليس توصية شراء أو بيع.'};
 return report;
}
export function nonSessionReport(date,calendar,last){
 const s=Calendar.status(calendar,date),holiday=s.state==='OFFICIAL_HOLIDAY'||s.state==='WEEKEND';
 return {schema:4,id:date,kind:'daily',date,sessionDay:dayName(date),report_type:holiday?'non_trading_day':'pending_session',status:holiday?'لا توجد جلسة تداول — '+s.label:'بانتظار بيانات جلسة موثقة',title:'التقرير اليومي — '+dayName(date)+' '+date,subtitle:holiday?'تقرير عطلة؛ آخر إغلاق متاح بتاريخ '+(last?.date||'غير متاح'):'لا يتوفر إغلاق مؤرخ لليوم؛ لم تُستخدم أسعار جلسة سابقة كإغلاق جديد.',prepared_by:'Codex',last_session_date:last?.date||null,calendar_status:s,generated_from:{file:'market-calendar.json',snapshot_updated_at:calendar.verified_at},audit:{audited:true,review_version:4,policy:'لا تنشأ أسعار أو نسب صعود وهبوط أو حجم تداول ليوم بلا جلسة.',notes:[s.label,'الموعد المعتاد التالي: '+(s.event?.resume_date||Calendar.nextSession(calendar,date)),calendar.coverage]},session_analysis:{headline:s.label,nature:holiday?'لا توجد جلسة لهذا التاريخ؛ لا يُحتسب ربح يومي أو نشاط تداول صفري مصطنع.':'لم تصل بيانات المصدر اللازمة لإنشاء تقرير إغلاق.',liquidity:'غير منطبق',tomorrow:'تستأنف الجلسات المعتادة '+(s.event?.resume_date||Calendar.nextSession(calendar,date))},stocks:{},indices:{},funds:[],fx_gold:{},portfolio_analysis:[],market_summary:summary({},{}),sources:s.event?.sources||[],disclaimer:'تعرض أسعار آخر جلسة في تقريرها الأصلي فقط.'};
}
export {summary,reading};
